{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/ismaskingdebugenabled()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/ismaskingdebugenabled()"]}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isMaskingDebugEnabled()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:objc(cs)EXPDBA(cm)isMaskingDebugEnabled","title":"isMaskingDebugEnabled()","modules":[{"name":"EXPDBA"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isMaskingDebugEnabled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isMaskingDebugEnabled"}],"symbolKind":"method","platforms":[{"introducedAt":"13.0","beta":false,"unavailable":false,"name":"iOS","deprecated":false}]},"abstract":[{"type":"text","text":"Checks if masking debug is enabled."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isMaskingDebugEnabled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"YES if enabled, NO otherwise","type":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"title":"EXPDBA","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EXPDBA","kind":"identifier"}],"url":"\/documentation\/expdba\/expdba","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"text":" ","type":"text"},{"text":"primary EXPCore.framework.","type":"text"}]},"doc://com.verint.xm.dba/documentation/EXPDBA":{"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","url":"\/documentation\/expdba","title":"EXPDBA","abstract":[],"type":"topic","role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/isMaskingDebugEnabled()":{"role":"symbol","abstract":[{"type":"text","text":"Checks if masking debug is enabled."}],"title":"isMaskingDebugEnabled()","type":"topic","url":"\/documentation\/expdba\/expdba\/ismaskingdebugenabled()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isMaskingDebugEnabled"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isMaskingDebugEnabled","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isMaskingDebugEnabled()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isMaskingDebugEnabled"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"isMaskingDebugEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isMaskingDebugEnabled"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"EXPDBA","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"kind":"identifier","text":"EXPDBA"}],"op":"replace"},{"op":"replace","value":"isMaskingDebugEnabled","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isMaskingDebugEnabled()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"isMaskingDebugEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isMaskingDebugEnabled()\/fragments","op":"replace"}]}]}