{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maskedViews"},{"text":"() -> [","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"EXPDBA"}],"navigatorTitle":[{"kind":"identifier","text":"maskedViews"}],"externalID":"c:objc(cs)EXPDBA(cm)maskedViews","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskedViews"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"platforms":[{"introducedAt":"13.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method","title":"maskedViews()"},"sections":[],"abstract":[{"type":"text","text":"Gets the list of masked views."}],"variants":[{"paths":["\/documentation\/expdba\/expdba\/maskedviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/maskedviews()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskedViews()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","url":"\/documentation\/expdba","title":"EXPDBA","abstract":[],"type":"topic","role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"title":"EXPDBA","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EXPDBA","kind":"identifier"}],"url":"\/documentation\/expdba\/expdba","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"text":" ","type":"text"},{"text":"primary EXPCore.framework.","type":"text"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/maskedViews()":{"title":"maskedViews()","type":"topic","url":"\/documentation\/expdba\/expdba\/maskedviews()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maskedViews"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskedViews()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"maskedViews","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"kind":"symbol","abstract":[{"text":"Gets the list of masked views.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"maskedViews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"maskedViews"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"maskedViews"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","value":"EXPDBA"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"kind":"identifier","text":"EXPDBA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1maskedViews()\/title","value":"maskedViews"},{"value":[{"text":"+ ","kind":"text"},{"text":"maskedViews","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1maskedViews()\/fragments","op":"replace"}]}]}