{"abstract":[{"text":"Enables recording through use of the API or an implemented custom prompt. Includes additional options such as recording for one session only.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setRecordingPermission","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"permissionResponse"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@DBAPermissionResponse","kind":"typeIdentifier","text":"DBAPermissionResponse","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"permissionResponse","content":[{"inlineContent":[{"type":"text","text":"The response selected. Values include"},{"type":"text","text":" "},{"text":"DBAPermissionResponseAllowedOnce, DBAPermissionResponseAllowedAlways, DBAPermissionResponseRejected, DBAPermissionResponseUndefined.","type":"text"},{"text":" ","type":"text"},{"text":"Selection persists between sessions (with the exception of DBAPermissionResponseAllowedOnce).","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/setrecordingpermission(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/setrecordingpermission(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setRecordingPermission(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Type Method","modules":[{"name":"EXPDBA"}],"externalID":"c:objc(cs)EXPDBA(cm)setRecordingPermission:","platforms":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setRecordingPermission"},{"text":"(","kind":"text"},{"text":"DBAPermissionResponse","kind":"typeIdentifier","preciseIdentifier":"c:@E@DBAPermissionResponse"},{"kind":"text","text":")"}],"title":"setRecordingPermission(_:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"setRecordingPermission:"}]},"sections":[],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DBAPermissionResponse","kind":"identifier"}],"url":"\/documentation\/expdba\/dbapermissionresponse","abstract":[],"type":"topic","title":"DBAPermissionResponse","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DBAPermissionResponse","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","url":"\/documentation\/expdba","title":"EXPDBA","abstract":[],"type":"topic","role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"title":"EXPDBA","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EXPDBA","kind":"identifier"}],"url":"\/documentation\/expdba\/expdba","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"text":" ","type":"text"},{"text":"primary EXPCore.framework.","type":"text"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/setRecordingPermission(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setRecordingPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DBAPermissionResponse","preciseIdentifier":"c:@E@DBAPermissionResponse"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setRecordingPermission:","kind":"identifier"}],"kind":"symbol","title":"setRecordingPermission(_:)","type":"topic","abstract":[{"text":"Enables recording through use of the API or an implemented custom prompt. Includes additional options such as recording for one session only.","type":"text"}],"url":"\/documentation\/expdba\/expdba\/setrecordingpermission(_:)","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setRecordingPermission(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"setRecordingPermission:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"setRecordingPermission:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"setRecordingPermission:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@DBAPermissionResponse","text":"DBAPermissionResponse","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"permissionResponse","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DBAPermissionResponse","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title"},{"value":[{"text":"DBAPermissionResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments"},{"value":"EXPDBA","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"kind":"identifier","text":"EXPDBA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setRecordingPermission(_:)\/title","value":"setRecordingPermission:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setRecordingPermission(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setRecordingPermission:","kind":"identifier"}]}]}]}