{"kind":"symbol","identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithAbort(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"digitalSurveyNotSubmittedWithAbort","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"digitalSurveyNotSubmittedWithAbort:","kind":"identifier"}],"role":"symbol","required":true,"modules":[{"name":"EXPDigital"}],"externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveyNotSubmittedWithAbort:","title":"digitalSurveyNotSubmittedWithAbort(_:)","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveyNotSubmittedWithAbort"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"surveyName","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithabort(_:)"]},{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithabort(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"title":"EXPDigital","role":"collection","kind":"symbol","url":"\/documentation\/expdigital","abstract":[],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotSubmittedWithAbort(_:)":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"digitalSurveyNotSubmittedWithAbort:","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithAbort(_:)","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithabort(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"digitalSurveyNotSubmittedWithAbort","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"digitalSurveyNotSubmittedWithAbort(_:)","required":true,"abstract":[]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"abstract":[{"text":"Objects that adopt the","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"},{"text":" protocol receive ","type":"text"},{"code":"Digital","type":"codeVoice"},{"type":"text","text":" lifecycle events"}],"navigatorTitle":[{"text":"DigitalDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/expdigital\/digitaldelegate","title":"DigitalDelegate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"digitalSurveyNotSubmittedWithAbort:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyNotSubmittedWithAbort:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"digitalSurveyNotSubmittedWithAbort:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"surveyName","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"digitalSurveyNotSubmittedWithAbort:","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithAbort(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"digitalSurveyNotSubmittedWithAbort:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithAbort(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","op":"replace","value":"DigitalDelegate"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","value":[{"kind":"identifier","text":"DigitalDelegate"}],"op":"replace"}]}]}