{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveystatusretrieved(_:enabled:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveystatusretrieved(_:enabled:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalSurveyStatusRetrieved"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"surveyName","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"required":true,"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalSurveyStatusRetrieved","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"enabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"digitalSurveyStatusRetrieved:enabled:"}],"modules":[{"name":"EXPDigital"}],"title":"digitalSurveyStatusRetrieved(_:enabled:)","roleHeading":"Instance Method","externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveyStatusRetrieved:enabled:"},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyStatusRetrieved(_:enabled:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyStatusRetrieved(_:enabled:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyStatusRetrieved(_:enabled:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalSurveyStatusRetrieved"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"enabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"digitalSurveyStatusRetrieved:enabled:","kind":"identifier"}],"title":"digitalSurveyStatusRetrieved(_:enabled:)","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveystatusretrieved(_:enabled:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"url":"\/documentation\/expdigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","role":"collection","title":"EXPDigital","abstract":[],"type":"topic"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"url":"\/documentation\/expdigital\/digitaldelegate","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","role":"symbol","title":"DigitalDelegate","abstract":[{"type":"text","text":"Objects that adopt the"},{"code":"DigitalDelegate","type":"codeVoice"},{"text":" protocol receive ","type":"text"},{"type":"codeVoice","code":"Digital"},{"type":"text","text":" lifecycle events"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"digitalSurveyStatusRetrieved:enabled:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"digitalSurveyStatusRetrieved:enabled:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"digitalSurveyStatusRetrieved:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"surveyName"},{"kind":"text","text":" "},{"text":"enabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"digitalSurveyStatusRetrieved:enabled:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyStatusRetrieved(_:enabled:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyStatusRetrieved(_:enabled:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyStatusRetrieved:enabled:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","value":"DigitalDelegate"},{"value":[{"kind":"identifier","text":"DigitalDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments"}]}]}