{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveySubmitted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"surveyName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveysubmitted(_:)"]},{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveysubmitted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveySubmitted(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveySubmitted"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveySubmitted:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"digitalSurveySubmitted:"}],"modules":[{"name":"EXPDigital"}],"title":"digitalSurveySubmitted(_:)","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveySubmitted(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalSurveySubmitted","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"digitalSurveySubmitted(_:)","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveySubmitted(_:)","kind":"symbol","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveysubmitted(_:)","navigatorTitle":[{"text":"digitalSurveySubmitted:","kind":"identifier"}],"abstract":[]},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital","role":"collection","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"title":"DigitalDelegate","url":"\/documentation\/expdigital\/digitaldelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","abstract":[{"text":"Objects that adopt the","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"type":"codeVoice","code":"Digital"},{"text":" lifecycle events","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"digitalSurveySubmitted:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveySubmitted:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"digitalSurveySubmitted:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"surveyName","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveySubmitted(_:)\/title","value":"digitalSurveySubmitted:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"digitalSurveySubmitted:"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveySubmitted(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","op":"replace","value":"DigitalDelegate"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","value":[{"text":"DigitalDelegate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}