{"sections":[],"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithNetworkError(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"digitalSurveyNotPresentedWithNetworkError","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"surveyName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"required":true,"role":"symbol","modules":[{"name":"EXPDigital"}],"externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveyNotPresentedWithNetworkError:","navigatorTitle":[{"kind":"identifier","text":"digitalSurveyNotPresentedWithNetworkError:"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"digitalSurveyNotPresentedWithNetworkError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"digitalSurveyNotPresentedWithNetworkError(_:)"},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"variants":[{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithnetworkerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithnetworkerror(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital","role":"collection","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"title":"DigitalDelegate","url":"\/documentation\/expdigital\/digitaldelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","abstract":[{"text":"Objects that adopt the","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"type":"codeVoice","code":"Digital"},{"text":" lifecycle events","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotPresentedWithNetworkError(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithNetworkError(_:)","type":"topic","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithnetworkerror(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveyNotPresentedWithNetworkError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"digitalSurveyNotPresentedWithNetworkError:","kind":"identifier"}],"title":"digitalSurveyNotPresentedWithNetworkError(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"digitalSurveyNotPresentedWithNetworkError:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"digitalSurveyNotPresentedWithNetworkError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"digitalSurveyNotPresentedWithNetworkError:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"surveyName","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"DigitalDelegate","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title"},{"value":[{"kind":"identifier","text":"DigitalDelegate"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithNetworkError(_:)\/title","op":"replace","value":"digitalSurveyNotPresentedWithNetworkError:"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithNetworkError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyNotPresentedWithNetworkError:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}