{"sections":[],"kind":"symbol","hierarchy":{"paths":[[]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]},{"identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionNumber","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionString"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"},"metadata":{"role":"collection","title":"EXPDigital","roleHeading":"Framework","symbolKind":"module","modules":[{"name":"EXPDigital"}],"externalID":"EXPDigital"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital"]}],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"url":"\/documentation\/expdigital\/digitalcomponent","type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","kind":"symbol","abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalComponent"}],"title":"DigitalComponent","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalVersionString":{"abstract":[{"type":"text","text":"Project version string for Digital."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"DigitalVersionString","kind":"identifier"},{"kind":"text","text":": <<error type>>"}],"title":"DigitalVersionString","url":"\/documentation\/expdigital\/digitalversionstring","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionString","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"DigitalVersionString","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalVersionNumber":{"url":"\/documentation\/expdigital\/digitalversionnumber","abstract":[{"type":"text","text":"Project version number for Digital."}],"title":"DigitalVersionNumber","type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalVersionNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"DigitalVersionNumber","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"title":"EXPDigital","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/expdigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"title":"DigitalDelegate","type":"topic","role":"symbol","url":"\/documentation\/expdigital\/digitaldelegate","abstract":[{"type":"text","text":"Objects that adopt the"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"type":"codeVoice","code":"Digital"},{"type":"text","text":" lifecycle events"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalDelegate"}],"navigatorTitle":[{"text":"DigitalDelegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"],"title":"Classes"},{"identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionNumber","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":"DigitalComponent","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","op":"replace"},{"value":[{"text":"DigitalComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionString\/title","value":"DigitalVersionString"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionString\/fragments","value":[{"text":"DigitalVersionString","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionNumber\/title","value":"DigitalVersionNumber"},{"op":"replace","value":[{"kind":"identifier","text":"DigitalVersionNumber"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionNumber\/fragments"},{"value":"DigitalDelegate","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","value":[{"text":"DigitalDelegate","kind":"identifier"}],"op":"replace"}]}]}