{"kind":"symbol","metadata":{"navigatorTitle":[{"text":"isRecording","kind":"identifier"}],"externalID":"c:objc(cs)EXPDBA(cm)isRecording","symbolKind":"method","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRecording","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","title":"isRecording()","platforms":[{"beta":false,"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0"}],"modules":[{"name":"EXPDBA"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/isrecording()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/isrecording()"]}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isRecording()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isRecording","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"YES if DBA is recording, NO if DBA is not recording"}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Checks if DBA is recording.","type":"text"}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EXPDBA","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"kind":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"text":"primary EXPCore.framework.","type":"text"}],"url":"\/documentation\/expdba\/expdba","title":"EXPDBA","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","role":"symbol","type":"topic"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","title":"EXPDBA","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/expdba","abstract":[]},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/isRecording()":{"navigatorTitle":[{"text":"isRecording","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isRecording()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isRecording","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/expdba\/expdba\/isrecording()","type":"topic","title":"isRecording()","abstract":[{"text":"Checks if DBA is recording.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isRecording"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isRecording","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isRecording","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"EXPDBA","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","op":"replace"},{"value":[{"text":"EXPDBA","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments"},{"op":"replace","value":"isRecording","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isRecording()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isRecording()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"isRecording","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}