{"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/resetRecordingPermission()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetRecordingPermission","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"If requestBeginRecording is called after permissions are reset, the default permission prompt will be displayed.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/resetrecordingpermission()"]},{"paths":["\/documentation\/expdba\/expdba\/resetrecordingpermission()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Resets recording permission to the default value of ‘NotSet’."}],"sections":[],"metadata":{"externalID":"c:objc(cs)EXPDBA(cm)resetRecordingPermission","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetRecordingPermission"},{"kind":"text","text":"()"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"resetRecordingPermission","kind":"identifier"}],"roleHeading":"Type Method","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false}],"title":"resetRecordingPermission()","modules":[{"name":"EXPDBA"}]},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"kind":"symbol","references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","title":"EXPDBA","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/expdba","abstract":[]},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EXPDBA","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"kind":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"text":"primary EXPCore.framework.","type":"text"}],"url":"\/documentation\/expdba\/expdba","title":"EXPDBA","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","role":"symbol","type":"topic"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/resetRecordingPermission()":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/resetRecordingPermission()","type":"topic","role":"symbol","navigatorTitle":[{"text":"resetRecordingPermission","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Resets recording permission to the default value of ‘NotSet’."}],"url":"\/documentation\/expdba\/expdba\/resetrecordingpermission()","title":"resetRecordingPermission()","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetRecordingPermission"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"resetRecordingPermission","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"resetRecordingPermission","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"resetRecordingPermission"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"EXPDBA","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"text":"EXPDBA","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1resetRecordingPermission()\/title","op":"replace","value":"resetRecordingPermission"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1resetRecordingPermission()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"resetRecordingPermission","kind":"identifier"}]}]}]}