{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unmaskView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"unmaskView:"}],"platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"}],"title":"unmaskView(_:)","roleHeading":"Type Method","modules":[{"name":"EXPDBA"}],"externalID":"c:objc(cs)EXPDBA(cm)unmaskView:","role":"symbol","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/unmaskView(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unmaskView"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"view"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The view to unmask","type":"text"}]}],"name":"view"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Removes the mask from a view in a DBA recording.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/unmaskview(_:)"]},{"paths":["\/documentation\/expdba\/expdba\/unmaskview(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","abstract":[{"text":"The EXPDBA class provides the main interface to the DBA module. This module requires the","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"primary EXPCore.framework."}],"title":"EXPDBA","url":"\/documentation\/expdba\/expdba","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EXPDBA","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/unmaskView(_:)":{"title":"unmaskView(_:)","kind":"symbol","url":"\/documentation\/expdba\/expdba\/unmaskview(_:)","abstract":[{"text":"Removes the mask from a view in a DBA recording.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"unmaskView:"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/unmaskView(_:)","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unmaskView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","url":"\/documentation\/expdba","abstract":[],"kind":"symbol","title":"EXPDBA","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"unmaskView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"unmaskView:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"unmaskView:"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"view","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"EXPDBA","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","op":"replace","value":[{"kind":"identifier","text":"EXPDBA"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1unmaskView(_:)\/title","value":"unmaskView:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"unmaskView:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1unmaskView(_:)\/fragments"}]}]}