{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-44mfh"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(initWithName:surveyId:origin:) ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"surveyId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"origin","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin","text":"EXPSDKEventOrigin"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"EXPSurveyManagement"}],"externalID":"c:@M@EXPSurveyManagement@objc(cs)SdkEvent(im)initWithName:surveyId:origin:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"surveyId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"text":"EXPSDKEventOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithName:surveyId:origin:","kind":"identifier"}],"title":"init(_:surveyId:origin:)"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent"]]},"variants":[{"paths":["\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-44mfh"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-44mfh"]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","url":"\/documentation\/expsurveymanagement","title":"EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/init(_:surveyId:origin:)-44mfh":{"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"surveyId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"text":"EXPSDKEventOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithName:surveyId:origin:","kind":"identifier"}],"abstract":[],"title":"init(_:surveyId:origin:)","url":"\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-44mfh","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-44mfh"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"role":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SdkEvent"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","title":"SdkEvent","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SdkEvent","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithName:surveyId:origin:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:surveyId:origin:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithName:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"text":"surveyId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"surveyId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"origin:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@EXPSDKEventOrigin","kind":"typeIdentifier","text":"EXPSDKEventOrigin"},{"kind":"text","text":") "},{"kind":"internalParam","text":"origin"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-44mfh\/title","value":"initWithName:surveyId:origin:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithName:surveyId:origin:"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-44mfh\/fragments"},{"op":"replace","value":"SdkEvent","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title"},{"value":[{"kind":"identifier","text":"SdkEvent"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}