{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithNetworkError(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"digitalSurveyNotSubmittedWithNetworkError(_:)","modules":[{"name":"EXPDigital"}],"symbolKind":"method","externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveyNotSubmittedWithNetworkError:","roleHeading":"Instance Method","navigatorTitle":[{"text":"digitalSurveyNotSubmittedWithNetworkError:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"digitalSurveyNotSubmittedWithNetworkError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithnetworkerror(_:)"]},{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithnetworkerror(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"digitalSurveyNotSubmittedWithNetworkError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"surveyName","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotSubmittedWithNetworkError(_:)":{"title":"digitalSurveyNotSubmittedWithNetworkError(_:)","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithNetworkError(_:)","kind":"symbol","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithnetworkerror(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalSurveyNotSubmittedWithNetworkError"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"digitalSurveyNotSubmittedWithNetworkError:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"role":"collection","type":"topic","title":"EXPDigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"role":"symbol","navigatorTitle":[{"text":"DigitalDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","kind":"symbol","title":"DigitalDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DigitalDelegate","kind":"identifier"}],"type":"topic","url":"\/documentation\/expdigital\/digitaldelegate","abstract":[{"type":"text","text":"Objects that adopt the"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"code":"Digital","type":"codeVoice"},{"type":"text","text":" lifecycle events"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"digitalSurveyNotSubmittedWithNetworkError:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyNotSubmittedWithNetworkError:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"digitalSurveyNotSubmittedWithNetworkError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"surveyName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithNetworkError(_:)\/title","value":"digitalSurveyNotSubmittedWithNetworkError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithNetworkError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyNotSubmittedWithNetworkError:","kind":"identifier"}]},{"op":"replace","value":"DigitalDelegate","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","value":[{"kind":"identifier","text":"DigitalDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}