{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedAlways"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expdba\/dbapermissionresponse\/allowedalways"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/dbapermissionresponse\/allowedalways"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedAlways","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedAlways"}],"title":"DBAPermissionResponse.allowedAlways","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@DBAPermissionResponse@DBAPermissionResponseAllowedAlways","modules":[{"name":"EXPDBA"}],"navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}]},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"]]},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"role":"collection","title":"EXPDBA","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","kind":"symbol","type":"topic","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"role":"symbol","title":"DBAPermissionResponse","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBAPermissionResponse"}],"abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponse"}],"url":"\/documentation\/expdba\/dbapermissionresponse"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/allowedAlways":{"role":"symbol","title":"DBAPermissionResponse.allowedAlways","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowedAlways"}],"abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedAlways","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}],"url":"\/documentation\/expdba\/dbapermissionresponse\/allowedalways"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DBAPermissionResponseAllowedAlways"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title","value":"DBAPermissionResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedAlways\/title","value":"DBAPermissionResponseAllowedAlways"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedAlways\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}