{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expdba\/dbapermissionresponse\/undefined"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/dbapermissionresponse\/undefined"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/undefined","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"title":"DBAPermissionResponse.undefined","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@DBAPermissionResponse@DBAPermissionResponseUndefined","modules":[{"name":"EXPDBA"}],"navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseUndefined"}]},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"]]},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/undefined":{"role":"symbol","title":"DBAPermissionResponse.undefined","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"undefined"}],"abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/undefined","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseUndefined"}],"url":"\/documentation\/expdba\/dbapermissionresponse\/undefined"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"role":"collection","title":"EXPDBA","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","kind":"symbol","type":"topic","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"role":"symbol","title":"DBAPermissionResponse","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBAPermissionResponse"}],"abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponse"}],"url":"\/documentation\/expdba\/dbapermissionresponse"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DBAPermissionResponseUndefined"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseUndefined"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DBAPermissionResponseUndefined"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1undefined\/title","value":"DBAPermissionResponseUndefined"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1undefined\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseUndefined"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title","value":"DBAPermissionResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}