{"metadata":{"title":"DBAPermissionResponse.allowedOnce","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowedOnce","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@DBAPermissionResponse@DBAPermissionResponseAllowedOnce","modules":[{"name":"EXPDBA"}],"navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseAllowedOnce"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"allowedOnce","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/expdba\/dbapermissionresponse\/allowedonce"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/dbapermissionresponse\/allowedonce"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedOnce"},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","title":"EXPDBA","kind":"symbol","url":"\/documentation\/expdba","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/allowedOnce":{"url":"\/documentation\/expdba\/dbapermissionresponse\/allowedonce","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedOnce","title":"DBAPermissionResponse.allowedOnce","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"allowedOnce","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseAllowedOnce"}],"abstract":[],"role":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"kind":"symbol","title":"DBAPermissionResponse","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DBAPermissionResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponse"}],"url":"\/documentation\/expdba\/dbapermissionresponse","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DBAPermissionResponseAllowedOnce","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DBAPermissionResponseAllowedOnce","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DBAPermissionResponseAllowedOnce"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DBAPermissionResponseAllowedOnce","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedOnce\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedOnce\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseAllowedOnce"}]},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title","value":"DBAPermissionResponse","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DBAPermissionResponse"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}