{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EXPPredictiveFacade.checkIfEligibleForSurvey()"},{"type":"text","text":"."}],"metadata":{"title":"checkIfEligibleForSurvey()","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkIfEligibleForSurvey","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)checkIfEligibleForSurvey","symbolKind":"method","modules":[{"name":"EXPSurveyManagement"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkIfEligibleForSurvey"}]},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkIfEligibleForSurvey"},{"text":"()","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/checkifeligibleforsurvey()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/checkifeligibleforsurvey()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/checkIfEligibleForSurvey()","interfaceLanguage":"swift"},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/checkIfEligibleForSurvey()":{"url":"\/documentation\/expsurveymanagement\/surveymanagement\/checkifeligibleforsurvey()","type":"topic","title":"checkIfEligibleForSurvey()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkIfEligibleForSurvey","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkIfEligibleForSurvey"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/checkIfEligibleForSurvey()","abstract":[],"role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","title":"EXPSurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","url":"\/documentation\/expsurveymanagement","kind":"symbol","role":"collection","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"type":"topic","title":"SurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","url":"\/documentation\/expsurveymanagement\/surveymanagement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"checkIfEligibleForSurvey","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkIfEligibleForSurvey"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkIfEligibleForSurvey"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"checkIfEligibleForSurvey","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1checkIfEligibleForSurvey()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"checkIfEligibleForSurvey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1checkIfEligibleForSurvey()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","value":"EXPSurveyManagement"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","value":[{"text":"EXPSurveyManagement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}