{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearUserData","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"clearUserData()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearUserData","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)clearUserData","modules":[{"name":"EXPSurveyManagement"}],"symbolKind":"method","navigatorTitle":[{"text":"clearUserData","kind":"identifier"}],"roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/clearuserdata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/clearuserdata()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"EXPPredictiveFacade.clearUserData()","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/clearUserData()"},"sections":[],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"type":"topic","title":"SurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","url":"\/documentation\/expsurveymanagement\/surveymanagement","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/clearUserData()":{"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/clearuserdata()","title":"clearUserData()","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"clearUserData","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/clearUserData()","navigatorTitle":[{"text":"clearUserData","kind":"identifier"}],"abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","title":"EXPSurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","url":"\/documentation\/expsurveymanagement","kind":"symbol","role":"collection","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"clearUserData","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"clearUserData"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"clearUserData","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"EXPSurveyManagement","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","op":"replace","value":[{"kind":"identifier","text":"EXPSurveyManagement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1clearUserData()\/title","value":"clearUserData"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1clearUserData()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"clearUserData","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}