{"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onSetupComplete()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/onsetupcomplete()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/onsetupcomplete()"]}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSetupComplete"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onSetupComplete","kind":"identifier"},{"text":"()","kind":"text"}],"title":"onSetupComplete()","modules":[{"name":"EXPSurveyManagement"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onSetupComplete"}],"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(im)onSetupComplete","role":"symbol","roleHeading":"Instance Method"},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"abstract":[],"title":"EXPSurveyManagement","role":"collection","kind":"symbol","url":"\/documentation\/expsurveymanagement","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"type":"topic","role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement","kind":"symbol","navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","title":"SurveyManagement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}],"abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/onSetupComplete()":{"title":"onSetupComplete()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSetupComplete"},{"text":"()","kind":"text"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/onsetupcomplete()","kind":"symbol","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onSetupComplete()","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onSetupComplete"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"onSetupComplete","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onSetupComplete"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onSetupComplete","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"EXPSurveyManagement","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","op":"replace","value":[{"text":"EXPSurveyManagement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onSetupComplete()\/title","op":"replace","value":"onSetupComplete"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onSetupComplete()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onSetupComplete","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}