{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onUnhandledException()"},"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/onunhandledexception()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/onunhandledexception()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(im)onUnhandledException","title":"onUnhandledException()","navigatorTitle":[{"text":"onUnhandledException","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"EXPSurveyManagement"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"kind":"text","text":"()"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/onUnhandledException()":{"url":"\/documentation\/expsurveymanagement\/surveymanagement\/onunhandledexception()","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onUnhandledException()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"text":"()","kind":"text"}],"title":"onUnhandledException()","navigatorTitle":[{"kind":"identifier","text":"onUnhandledException"}],"kind":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"url":"\/documentation\/expsurveymanagement\/surveymanagement","abstract":[],"navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SurveyManagement"}],"kind":"symbol","title":"SurveyManagement","type":"topic","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"url":"\/documentation\/expsurveymanagement","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","kind":"symbol","title":"EXPSurveyManagement","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onUnhandledException","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUnhandledException"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onUnhandledException()\/title","value":"onUnhandledException"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUnhandledException"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onUnhandledException()\/fragments"},{"value":"EXPSurveyManagement","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","op":"replace"},{"op":"replace","value":[{"text":"EXPSurveyManagement","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments"}]}]}