{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEvents()"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"EXPPredictiveFacade.resetSignificantEvents()","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetSignificantEvents","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/resetsignificantevents()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/resetsignificantevents()"]}],"metadata":{"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)resetSignificantEvents","title":"resetSignificantEvents()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetSignificantEvents"},{"kind":"text","text":"()"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method","modules":[{"name":"EXPSurveyManagement"}],"navigatorTitle":[{"text":"resetSignificantEvents","kind":"identifier"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"type":"topic","role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement","kind":"symbol","navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","title":"SurveyManagement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}],"abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/resetSignificantEvents()":{"title":"resetSignificantEvents()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetSignificantEvents"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/resetsignificantevents()","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEvents()","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resetSignificantEvents"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"abstract":[],"title":"EXPSurveyManagement","role":"collection","kind":"symbol","url":"\/documentation\/expsurveymanagement","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"resetSignificantEvents","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"resetSignificantEvents"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"resetSignificantEvents","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"EXPSurveyManagement","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title"},{"value":[{"kind":"identifier","text":"EXPSurveyManagement"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetSignificantEvents()\/title","value":"resetSignificantEvents","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"resetSignificantEvents"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetSignificantEvents()\/fragments"}]}]}