{"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/showsurvey(forname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/showsurvey(forname:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(forName:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showSurvey"},{"kind":"text","text":"("},{"text":"forName","kind":"externalParam"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Type Method","title":"showSurvey(forName:)","navigatorTitle":[{"text":"showSurveyForName:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSurvey"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"modules":[{"name":"EXPSurveyManagement"}],"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)showSurveyForName:","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","url":"\/documentation\/expsurveymanagement","abstract":[],"role":"collection","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","kind":"symbol","title":"EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/showSurvey(forName:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(forName:)","type":"topic","url":"\/documentation\/expsurveymanagement\/surveymanagement\/showsurvey(forname:)","navigatorTitle":[{"text":"showSurveyForName:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"showSurvey(forName:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSurvey"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"url":"\/documentation\/expsurveymanagement\/surveymanagement","abstract":[],"navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SurveyManagement"}],"kind":"symbol","title":"SurveyManagement","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"showSurveyForName:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"showSurveyForName:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"showSurveyForName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showSurvey(forName:)\/title","op":"replace","value":"showSurveyForName:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showSurvey(forName:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"showSurveyForName:","kind":"identifier"}],"op":"replace"},{"value":"EXPSurveyManagement","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","value":[{"kind":"identifier","text":"EXPSurveyManagement"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}