{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setDigitalListener(delegate:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setDigitalListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate","text":"DigitalDelegate","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"delegate","content":[{"inlineContent":[{"text":"an object conforming to ","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"}],"type":"paragraph"}]}]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"setDigitalListenerWithDelegate:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDigitalListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate","kind":"typeIdentifier","text":"DigitalDelegate"},{"text":")","kind":"text"}],"title":"setDigitalListener(delegate:)","symbolKind":"method","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(cm)setDigitalListenerWithDelegate:","modules":[{"name":"EXPDigital"}]},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"sections":[],"abstract":[{"text":"Sets a delegate for Digital survey operations","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/setdigitallistener(delegate:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/setdigitallistener(delegate:)"]}],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"url":"\/documentation\/expdigital","role":"collection","abstract":[],"type":"topic","kind":"symbol","title":"EXPDigital","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"abstract":[{"type":"text","text":"Objects that adopt the"},{"type":"codeVoice","code":"DigitalDelegate"},{"text":" protocol receive ","type":"text"},{"type":"codeVoice","code":"Digital"},{"type":"text","text":" lifecycle events"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DigitalDelegate","kind":"identifier"}],"url":"\/documentation\/expdigital\/digitaldelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}],"title":"DigitalDelegate","role":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/setDigitalListener(delegate:)":{"navigatorTitle":[{"text":"setDigitalListenerWithDelegate:","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setDigitalListener(delegate:)","url":"\/documentation\/expdigital\/digitalcomponent\/setdigitallistener(delegate:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDigitalListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DigitalDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Sets a delegate for Digital survey operations"}],"role":"symbol","title":"setDigitalListener(delegate:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","title":"DigitalComponent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DigitalComponent","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"type":"topic","url":"\/documentation\/expdigital\/digitalcomponent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setDigitalListenerWithDelegate:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setDigitalListenerWithDelegate:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setDigitalListenerWithDelegate:"},{"kind":"text","text":"("},{"text":"id<DigitalDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EXPDigital@objc(pl)DigitalDelegate"},{"text":") ","kind":"text"},{"text":"delegate","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","value":"DigitalDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","value":[{"kind":"identifier","text":"DigitalDelegate"}]},{"op":"replace","value":"setDigitalListenerWithDelegate:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setDigitalListener(delegate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setDigitalListener(delegate:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setDigitalListenerWithDelegate:"}]},{"value":"DigitalComponent","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","op":"replace","value":[{"text":"DigitalComponent","kind":"identifier"}]}]}]}