{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rejected","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/rejected"},"metadata":{"externalID":"c:@E@DBAPermissionResponse@DBAPermissionResponseRejected","symbolKind":"case","roleHeading":"Case","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseRejected"}],"title":"DBAPermissionResponse.rejected","modules":[{"name":"EXPDBA"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rejected"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/dbapermissionresponse\/rejected"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/dbapermissionresponse\/rejected"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","title":"EXPDBA","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/expdba","abstract":[]},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"abstract":[],"title":"DBAPermissionResponse","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DBAPermissionResponse","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponse"}],"url":"\/documentation\/expdba\/dbapermissionresponse"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/rejected":{"abstract":[],"role":"symbol","url":"\/documentation\/expdba\/dbapermissionresponse\/rejected","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rejected"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/rejected","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseRejected"}],"title":"DBAPermissionResponse.rejected"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DBAPermissionResponseRejected","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseRejected"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DBAPermissionResponseRejected","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title","value":"DBAPermissionResponse","op":"replace"},{"op":"replace","value":[{"text":"DBAPermissionResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1rejected\/title","value":"DBAPermissionResponseRejected"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1rejected\/fragments","value":[{"text":"DBAPermissionResponseRejected","kind":"identifier"}]}]}]}