{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldSkipPoolingCheck","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"EXPPredictiveFacade.shouldSkipPoolingCheck()"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Type Method","externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)shouldSkipPoolingCheck","modules":[{"name":"EXPSurveyManagement"}],"title":"shouldSkipPoolingCheck()","navigatorTitle":[{"text":"shouldSkipPoolingCheck","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldSkipPoolingCheck","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/shouldSkipPoolingCheck()","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/shouldskippoolingcheck()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/shouldskippoolingcheck()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/shouldSkipPoolingCheck()":{"role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldSkipPoolingCheck"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"shouldSkipPoolingCheck","kind":"identifier"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/shouldskippoolingcheck()","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/shouldSkipPoolingCheck()","type":"topic","title":"shouldSkipPoolingCheck()"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","kind":"symbol","role":"collection","url":"\/documentation\/expsurveymanagement","title":"EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"url":"\/documentation\/expsurveymanagement\/surveymanagement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SurveyManagement","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","title":"SurveyManagement","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"shouldSkipPoolingCheck","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"shouldSkipPoolingCheck"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"shouldSkipPoolingCheck"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"shouldSkipPoolingCheck","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1shouldSkipPoolingCheck()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1shouldSkipPoolingCheck()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"shouldSkipPoolingCheck","kind":"identifier"}]},{"value":"EXPSurveyManagement","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","value":[{"text":"EXPSurveyManagement","kind":"identifier"}]}]}]}