{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionNumber"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalVersionNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Project version number for Digital."}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"]]},"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"DigitalVersionNumber","kind":"identifier"}],"externalID":"c:@DigitalVersionNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Global Variable","symbolKind":"var","title":"DigitalVersionNumber","role":"symbol","modules":[{"name":"EXPDigital"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/expdigital\/digitalversionnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdigital\/digitalversionnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","type":"topic","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/expdigital","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalVersionNumber":{"navigatorTitle":[{"text":"DigitalVersionNumber","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","title":"DigitalVersionNumber","url":"\/documentation\/expdigital\/digitalversionnumber","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionNumber","abstract":[{"type":"text","text":"Project version number for Digital."}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DigitalVersionNumber"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DigitalVersionNumber","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"text":"DigitalVersionNumber","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DigitalVersionNumber","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionNumber\/title"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionNumber\/fragments","value":[{"text":"DigitalVersionNumber","kind":"identifier"}],"op":"replace"}]}]}