{"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"NSCoding.encode(with:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent"]]},"metadata":{"navigatorTitle":[{"text":"encodeWithCoder:","kind":"identifier"}],"modules":[{"name":"EXPSurveyManagement"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"title":"encode(with:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@EXPSurveyManagement@objc(cs)SdkEvent(im)encodeWithCoder:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/encode(with:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/encode(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/encode(with:)"]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/encode(with:)":{"navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"title":"encode(with:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/encode(with:)","url":"\/documentation\/expsurveymanagement\/sdkevent\/encode(with:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","type":"topic","abstract":[],"role":"symbol","title":"SdkEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SdkEvent"}],"url":"\/documentation\/expsurveymanagement\/sdkevent","navigatorTitle":[{"text":"SdkEvent","kind":"identifier"}],"kind":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","type":"topic","title":"EXPSurveyManagement","kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"encodeWithCoder:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"encodeWithCoder:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"encodeWithCoder:"},{"text":"(","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1encode(with:)\/title","op":"replace","value":"encodeWithCoder:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1encode(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeWithCoder:"}],"op":"replace"},{"value":"SdkEvent","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title","op":"replace"},{"value":[{"text":"SdkEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}