{"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-44mfh","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-8w8jr","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(coder:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(from:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/event"]},{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/asJSON()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/encode(with:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setEventTrigger(eventTrigger:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setNoficationType(notificationType:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/supportsSecureCoding"],"title":"Type Properties"}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent"]},{"paths":["\/documentation\/expsurveymanagement\/sdkevent"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SdkEvent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SdkEvent"}],"modules":[{"name":"EXPSurveyManagement"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@EXPSurveyManagement@objc(cs)SdkEvent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SdkEvent"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SdkEvent"}],"languages":["swift"]}]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSCoding","doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSSecureCoding","doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSObject","doc:\/\/com.verint.xm.EXPSurveyManagement\/s7CVarArgP","doc:\/\/com.verint.xm.EXPSurveyManagement\/s28CustomDebugStringConvertibleP","doc:\/\/com.verint.xm.EXPSurveyManagement\/s23CustomStringConvertibleP","doc:\/\/com.verint.xm.EXPSurveyManagement\/Se","doc:\/\/com.verint.xm.EXPSurveyManagement\/SE","doc:\/\/com.verint.xm.EXPSurveyManagement\/SQ","doc:\/\/com.verint.xm.EXPSurveyManagement\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"references":{"doc://com.verint.xm.EXPSurveyManagement/objc(pl)NSSecureCoding":{"type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSSecureCoding","title":"NSSecureCoding"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/init(_:surveyId:origin:)-44mfh":{"role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"surveyId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"text":"EXPSDKEventOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithName:surveyId:origin:","kind":"identifier"}],"abstract":[],"title":"init(_:surveyId:origin:)","url":"\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-44mfh","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-44mfh"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","url":"\/documentation\/expsurveymanagement","title":"EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/supportsSecureCoding":{"role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"supportsSecureCoding"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"supportsSecureCoding"}],"abstract":[],"title":"supportsSecureCoding","url":"\/documentation\/expsurveymanagement\/sdkevent\/supportssecurecoding","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/supportsSecureCoding"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/init(coder:)":{"abstract":[],"url":"\/documentation\/expsurveymanagement\/sdkevent\/init(coder:)","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(coder:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","title":"init(coder:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"role":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SdkEvent"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","title":"SdkEvent","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SdkEvent","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/encode(with:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"encodeWithCoder:","kind":"identifier"}],"abstract":[],"title":"encode(with:)","url":"\/documentation\/expsurveymanagement\/sdkevent\/encode(with:)","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/encode(with:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/asJSON()":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"asJSON","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"asJSON","kind":"identifier"}],"abstract":[],"title":"asJSON()","url":"\/documentation\/expsurveymanagement\/sdkevent\/asjson()","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/asJSON()"},"doc://com.verint.xm.EXPSurveyManagement/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/SH","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/init(_:surveyId:origin:)-8w8jr":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EXPSDKEventType","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventType"},{"kind":"text","text":", "},{"text":"surveyId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"origin","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin","text":"EXPSDKEventOrigin"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithEventType:surveyId:origin:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-8w8jr","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-8w8jr","title":"init(_:surveyId:origin:)"},"doc://com.verint.xm.EXPSurveyManagement/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/setNoficationType(notificationType:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setNoficationType","kind":"identifier"},{"text":"(","kind":"text"},{"text":"notificationType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"setNoficationTypeWithNotificationType:"}],"abstract":[],"title":"setNoficationType(notificationType:)","url":"\/documentation\/expsurveymanagement\/sdkevent\/setnoficationtype(notificationtype:)","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setNoficationType(notificationType:)"},"doc://com.verint.xm.EXPSurveyManagement/Se":{"type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/Se","title":"Swift.Decodable"},"doc://com.verint.xm.EXPSurveyManagement/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/init(from:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(from:)","kind":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent\/init(from:)","role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.verint.xm.EXPSurveyManagement/objc(pl)NSObject":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/setEventTrigger(eventTrigger:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setEventTrigger(eventTrigger:)","kind":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent\/seteventtrigger(eventtrigger:)","role":"symbol","title":"setEventTrigger(eventTrigger:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setEventTrigger","kind":"identifier"},{"text":"(","kind":"text"},{"text":"eventTrigger","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventTrigger","text":"EXPSDKEventTrigger"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setEventTriggerWithEventTrigger:","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/event":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/event","url":"\/documentation\/expsurveymanagement\/sdkevent\/event","kind":"symbol","role":"symbol","title":"event","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"event","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/SQ","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(cs)NSObject","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/SE":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/SE","title":"Swift.Encodable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SdkEvent","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SdkEvent"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SdkEvent","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/event"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/asJSON()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/encode(with:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-44mfh","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-8w8jr","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(coder:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setEventTrigger(eventTrigger:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setNoficationType(notificationType:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/supportsSecureCoding"]}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSSecureCoding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SdkEvent","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-44mfh\/title","value":"initWithName:surveyId:origin:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-44mfh\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithName:surveyId:origin:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"supportsSecureCoding","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1supportsSecureCoding\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1supportsSecureCoding\/fragments","op":"replace","value":[{"kind":"identifier","text":"supportsSecureCoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(coder:)\/fragments"},{"op":"replace","value":"SdkEvent","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments","value":[{"text":"SdkEvent","kind":"identifier"}],"op":"replace"},{"value":"encodeWithCoder:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1encode(with:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"encodeWithCoder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1encode(with:)\/fragments"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1asJSON()\/title","value":"asJSON","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1asJSON()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"asJSON","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-8w8jr\/title","value":"initWithEventType:surveyId:origin:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-8w8jr\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEventType:surveyId:origin:"}],"op":"replace"},{"value":"setNoficationTypeWithNotificationType:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1setNoficationType(notificationType:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setNoficationTypeWithNotificationType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1setNoficationType(notificationType:)\/fragments"},{"value":"setEventTriggerWithEventTrigger:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1setEventTrigger(eventTrigger:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1setEventTrigger(eventTrigger:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setEventTriggerWithEventTrigger:","kind":"identifier"}]},{"value":"event","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1event\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1event\/fragments","op":"replace","value":[{"kind":"identifier","text":"event"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}