{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"metadata":{"externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(im)onUnhandledException","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"kind":"text","text":"()"}],"role":"symbol","symbolKind":"method","modules":[{"name":"EXPDigital"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"onUnhandledException","kind":"identifier"}],"title":"onUnhandledException()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onUnhandledException()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/onunhandledexception()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/onunhandledexception()"]}],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","type":"topic","role":"collection","abstract":[],"kind":"symbol","url":"\/documentation\/expdigital","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/onUnhandledException()":{"type":"topic","role":"symbol","title":"onUnhandledException()","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"onUnhandledException"}],"url":"\/documentation\/expdigital\/digitalcomponent\/onunhandledexception()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUnhandledException","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onUnhandledException()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"role":"symbol","title":"DigitalComponent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalComponent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DigitalComponent"}],"type":"topic","url":"\/documentation\/expdigital\/digitalcomponent","abstract":[{"text":"The primary interface for showing Verint Digital surveys","type":"text"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onUnhandledException","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUnhandledException","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUnhandledException"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onUnhandledException()\/title","value":"onUnhandledException","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onUnhandledException","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onUnhandledException()\/fragments"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","value":"DigitalComponent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","value":[{"text":"DigitalComponent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}