{"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate"]]},"sections":[],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/hooverDataSent()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hooverDataSent","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"hooverDataSent","kind":"identifier"}],"role":"symbol","title":"hooverDataSent()","roleHeading":"Instance Method","required":true,"externalID":"c:@M@EXPDBA@objc(pl)DBAHooverConnectionDelegate(im)hooverDataSent","modules":[{"name":"EXPDBA"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hooverDataSent","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate\/hooverdatasent()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate\/hooverdatasent()"]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate":{"type":"topic","url":"\/documentation\/expdba\/dbahooverconnectiondelegate","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate","title":"DBAHooverConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"navigatorTitle":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","type":"topic","role":"collection","title":"EXPDBA","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate/hooverDataSent()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hooverDataSent","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hooverDataSent"}],"type":"topic","title":"hooverDataSent()","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/hooverDataSent()","abstract":[],"required":true,"url":"\/documentation\/expdba\/dbahooverconnectiondelegate\/hooverdatasent()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"hooverDataSent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hooverDataSent"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"hooverDataSent"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/title","value":"DBAHooverConnectionDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/fragments"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1hooverDataSent()\/title","value":"hooverDataSent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1hooverDataSent()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hooverDataSent","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}