{"variants":[{"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketdisconnected()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketdisconnected()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketDisconnected()"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketDisconnected","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"websocketDisconnected"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"websocketDisconnected","kind":"identifier"}],"role":"symbol","title":"websocketDisconnected()","roleHeading":"Instance Method","externalID":"c:@M@EXPDBA@objc(pl)DBAHooverConnectionDelegate(im)websocketDisconnected","required":true,"modules":[{"name":"EXPDBA"}],"symbolKind":"method"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate/websocketDisconnected()":{"type":"topic","url":"\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketdisconnected()","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketDisconnected()","title":"websocketDisconnected()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"websocketDisconnected"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"websocketDisconnected","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","type":"topic","role":"collection","title":"EXPDBA","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate":{"type":"topic","url":"\/documentation\/expdba\/dbahooverconnectiondelegate","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate","title":"DBAHooverConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"navigatorTitle":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"websocketDisconnected"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"websocketDisconnected"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"websocketDisconnected","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"websocketDisconnected","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketDisconnected()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"websocketDisconnected"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketDisconnected()\/fragments","op":"replace"},{"value":"DBAHooverConnectionDelegate","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/title"},{"value":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/fragments"}]}]}