{"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabled()","interfaceLanguage":"swift"},"abstract":[{"text":"Checks whether a default Digital survey is enabled.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabled()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabled()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The status is returned to "},{"type":"codeVoice","code":"digitalSurveyStatusRetrieved"},{"text":" for the active","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DigitalDelegate"},{"text":". This method returns no value.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"metadata":{"role":"symbol","modules":[{"name":"EXPDigital"}],"title":"checkIfDigitalSurveyEnabled()","navigatorTitle":[{"text":"checkIfDigitalSurveyEnabled","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"},{"kind":"text","text":"()"}],"externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(cm)checkIfDigitalSurveyEnabled","roleHeading":"Type Method","symbolKind":"method"},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","type":"topic","abstract":[],"url":"\/documentation\/expdigital","title":"EXPDigital","role":"collection","kind":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/checkIfDigitalSurveyEnabled()":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabled()","abstract":[{"type":"text","text":"Checks whether a default Digital survey is enabled."}],"title":"checkIfDigitalSurveyEnabled()","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkIfDigitalSurveyEnabled","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"}],"url":"\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabled()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"title":"DigitalComponent","url":"\/documentation\/expdigital\/digitalcomponent","type":"topic","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DigitalComponent","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"checkIfDigitalSurveyEnabled"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"checkIfDigitalSurveyEnabled","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabled()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabled()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","value":"DigitalComponent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","value":[{"kind":"identifier","text":"DigitalComponent"}]}]}]}