{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DigitalDelegate","preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/expdigital\/digitalcomponent\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/delegate"]}],"kind":"symbol","metadata":{"title":"delegate","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DigitalDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate"},{"kind":"text","text":"?"}],"externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(cpy)delegate","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"modules":[{"name":"EXPDigital"}]},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/delegate","interfaceLanguage":"swift"},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"title":"DigitalDelegate","url":"\/documentation\/expdigital\/digitaldelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","abstract":[{"text":"Objects that adopt the","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"type":"codeVoice","code":"Digital"},{"text":" lifecycle events","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/delegate":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DigitalDelegate","preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","url":"\/documentation\/expdigital\/digitalcomponent\/delegate","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/delegate"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"navigatorTitle":[{"kind":"identifier","text":"DigitalComponent"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","role":"symbol","kind":"symbol","abstract":[{"text":"The primary interface for showing Verint Digital surveys","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DigitalComponent","kind":"identifier"}],"title":"DigitalComponent","url":"\/documentation\/expdigital\/digitalcomponent"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital","role":"collection","title":"EXPDigital"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"delegate","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"id<DigitalDelegate>","preciseIdentifier":"c:Qo@M@EXPDigital@objc(pl)DigitalDelegate","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"delegate","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","value":"DigitalDelegate"},{"value":[{"text":"DigitalDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","op":"replace"},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1delegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","value":"DigitalComponent"},{"value":[{"text":"DigitalComponent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}