{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEnabled","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/isEnabled()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(im)isEnabled","title":"isEnabled()","roleHeading":"Instance Method","modules":[{"name":"EXPDigital"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/isenabled()"]},{"paths":["\/documentation\/expdigital\/digitalcomponent\/isenabled()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/isEnabled()":{"url":"\/documentation\/expdigital\/digitalcomponent\/isenabled()","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/isEnabled()","title":"isEnabled()","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEnabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"url":"\/documentation\/expdigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","role":"collection","title":"EXPDigital","abstract":[],"type":"topic"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"url":"\/documentation\/expdigital\/digitalcomponent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalComponent","kind":"identifier"}],"title":"DigitalComponent","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"isEnabled","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEnabled"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isEnabled","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1isEnabled()\/title","value":"isEnabled"},{"value":[{"text":"- ","kind":"text"},{"text":"isEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1isEnabled()\/fragments"},{"value":"DigitalComponent","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DigitalComponent"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}