{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/resetstate()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/resetstate()"]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"method","title":"resetState()","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(im)resetState","navigatorTitle":[{"kind":"identifier","text":"resetState"}],"roleHeading":"Instance Method","modules":[{"name":"EXPDigital"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"resetState"},{"kind":"text","text":"()"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetState","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/resetState()"},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"title":"DigitalComponent","url":"\/documentation\/expdigital\/digitalcomponent","type":"topic","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DigitalComponent","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","type":"topic","abstract":[],"url":"\/documentation\/expdigital","title":"EXPDigital","role":"collection","kind":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/resetState()":{"title":"resetState()","url":"\/documentation\/expdigital\/digitalcomponent\/resetstate()","type":"topic","navigatorTitle":[{"text":"resetState","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resetState","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/resetState()"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"resetState"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"resetState","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"resetState","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DigitalComponent","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title"},{"value":[{"text":"DigitalComponent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1resetState()\/title","value":"resetState"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1resetState()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"resetState"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}