{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setup()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/expdigital\/digitalcomponent\/setup()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdigital\/digitalcomponent\/setup()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"setup()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"()"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setup"}],"roleHeading":"Instance Method","modules":[{"name":"EXPDigital"}],"externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(im)setup","symbolKind":"method"},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/setup()":{"type":"topic","url":"\/documentation\/expdigital\/digitalcomponent\/setup()","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setup()","title":"setup()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setup"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"setup","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"title":"EXPDigital","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/expdigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"url":"\/documentation\/expdigital\/digitalcomponent","type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","kind":"symbol","abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalComponent"}],"title":"DigitalComponent","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"setup","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setup","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"setup","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"setup","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setup()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setup()\/fragments","value":[{"kind":"text","text":"- "},{"text":"setup","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","value":"DigitalComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","value":[{"kind":"identifier","text":"DigitalComponent"}]}]}]}