{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate"]}],"metadata":{"roleHeading":"Protocol","role":"symbol","externalID":"c:@M@EXPDBA@objc(pl)DBAHooverConnectionDelegate","navigatorTitle":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"symbolKind":"protocol","title":"DBAHooverConnectionDelegate","modules":[{"name":"EXPDBA"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/hooverDataSent()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketConnected()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketDisconnected()"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA"]]},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate/websocketConnected()":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketconnected()","navigatorTitle":[{"kind":"identifier","text":"websocketConnected"}],"kind":"symbol","title":"websocketConnected()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"websocketConnected"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketConnected()"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","type":"topic","role":"collection","title":"EXPDBA","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate/websocketDisconnected()":{"type":"topic","url":"\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketdisconnected()","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketDisconnected()","title":"websocketDisconnected()","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"websocketDisconnected"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"websocketDisconnected","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate":{"type":"topic","url":"\/documentation\/expdba\/dbahooverconnectiondelegate","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate","title":"DBAHooverConnectionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"navigatorTitle":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate/hooverDataSent()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hooverDataSent","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hooverDataSent"}],"type":"topic","title":"hooverDataSent()","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/hooverDataSent()","abstract":[],"required":true,"url":"\/documentation\/expdba\/dbahooverconnectiondelegate\/hooverdatasent()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"DBAHooverConnectionDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/hooverDataSent()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketConnected()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketDisconnected()"],"title":"Instance Methods"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"websocketConnected","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketConnected()\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketConnected()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"websocketConnected","kind":"identifier"}]},{"value":"websocketDisconnected","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketDisconnected()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"websocketDisconnected","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketDisconnected()\/fragments"},{"value":"DBAHooverConnectionDelegate","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/fragments"},{"op":"replace","value":"hooverDataSent","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1hooverDataSent()\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1hooverDataSent()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hooverDataSent"}]}]}]}