{"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.verint.xm.dba\/SQ","doc:\/\/com.verint.xm.dba\/SH","doc:\/\/com.verint.xm.dba\/SY","doc:\/\/com.verint.xm.dba\/s8SendableP"]}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedAlways","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedOnce","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/rejected","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/undefined"]},{"identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/Equatable-Implementations","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/RawRepresentable-Implementations"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA"]]},"metadata":{"modules":[{"name":"EXPDBA"}],"externalID":"c:@E@DBAPermissionResponse","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponse"}],"role":"symbol","title":"DBAPermissionResponse","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DBAPermissionResponse","kind":"identifier"}],"roleHeading":"Enumeration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/dbapermissionresponse"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/dbapermissionresponse"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBAPermissionResponse"}]}]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/Equatable-Implementations":{"url":"\/documentation\/expdba\/dbapermissionresponse\/equatable-implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/Equatable-Implementations"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"title":"EXPDBA","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","url":"\/documentation\/expdba","kind":"symbol","type":"topic","role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/rejected":{"kind":"symbol","url":"\/documentation\/expdba\/dbapermissionresponse\/rejected","title":"DBAPermissionResponse.rejected","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/rejected","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rejected"}],"navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseRejected"}],"type":"topic"},"doc://com.verint.xm.dba/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.verint.xm.dba\/SH"},"doc://com.verint.xm.dba/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.verint.xm.dba\/s8SendableP"},"doc://com.verint.xm.dba/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.verint.xm.dba\/SQ"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/init(rawValue:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/init(rawValue:)","url":"\/documentation\/expdba\/dbapermissionresponse\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"init(rawValue:)","type":"topic"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/undefined":{"kind":"symbol","url":"\/documentation\/expdba\/dbapermissionresponse\/undefined","title":"DBAPermissionResponse.undefined","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/undefined","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"undefined","kind":"identifier"}],"navigatorTitle":[{"text":"DBAPermissionResponseUndefined","kind":"identifier"}],"type":"topic"},"doc://com.verint.xm.dba/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.verint.xm.dba\/SY"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/allowedOnce":{"kind":"symbol","url":"\/documentation\/expdba\/dbapermissionresponse\/allowedonce","title":"DBAPermissionResponse.allowedOnce","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedOnce","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allowedOnce"}],"navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseAllowedOnce"}],"type":"topic"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/allowedAlways":{"title":"DBAPermissionResponse.allowedAlways","navigatorTitle":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}],"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"allowedAlways","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedAlways","type":"topic","kind":"symbol","url":"\/documentation\/expdba\/dbapermissionresponse\/allowedalways"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse","navigatorTitle":[{"text":"DBAPermissionResponse","kind":"identifier"}],"url":"\/documentation\/expdba\/dbapermissionresponse","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DBAPermissionResponse"}],"role":"symbol","title":"DBAPermissionResponse","type":"topic"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/expdba\/dbapermissionresponse\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"DBAPermissionResponse","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"DBAPermissionResponse"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DBAPermissionResponse","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedAlways","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/allowedOnce","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/rejected","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse\/undefined"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DBAPermissionResponse","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"DBAPermissionResponseRejected","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1rejected\/title"},{"op":"replace","value":[{"text":"DBAPermissionResponseRejected","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1rejected\/fragments"},{"op":"replace","value":"DBAPermissionResponseUndefined","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1undefined\/title"},{"value":[{"text":"DBAPermissionResponseUndefined","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1undefined\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedOnce\/title","op":"replace","value":"DBAPermissionResponseAllowedOnce"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedOnce\/fragments","value":[{"text":"DBAPermissionResponseAllowedOnce","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedAlways\/title","op":"replace","value":"DBAPermissionResponseAllowedAlways"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse~1allowedAlways\/fragments","value":[{"kind":"identifier","text":"DBAPermissionResponseAllowedAlways"}]},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title","value":"DBAPermissionResponse","op":"replace"},{"value":[{"kind":"identifier","text":"DBAPermissionResponse"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments"}]}]}