{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EXPDBA"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/expdba\/expdba"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/expdba"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.verint.xm.dba\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.verint.xm.dba\/objc(pl)NSObject","doc:\/\/com.verint.xm.dba\/s7CVarArgP","doc:\/\/com.verint.xm.dba\/s28CustomDebugStringConvertibleP","doc:\/\/com.verint.xm.dba\/s23CustomStringConvertibleP","doc:\/\/com.verint.xm.dba\/SQ","doc:\/\/com.verint.xm.dba\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"role":"symbol","title":"EXPDBA","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EXPDBA"}],"symbolKind":"class","externalID":"c:objc(cs)EXPDBA","modules":[{"name":"EXPDBA"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isMaskingDebugEnabled()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isRecording()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/logPageChange(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskView(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskedViews()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/requestBeginRecording()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/resetRecordingPermission()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setMaskingDebugEnabled(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setRecordingPermission(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setTestGroupValue(_:forKey:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecording()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecordingAnd(onComplete:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/unmaskView(_:)"]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/stopRecording()":{"role":"symbol","title":"stopRecording()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops DBA recording."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopRecording"}],"url":"\/documentation\/expdba\/expdba\/stoprecording()"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/unmaskView(_:)":{"role":"symbol","title":"unmaskView(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmaskView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes the mask from a view in a DBA recording."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/unmaskView(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unmaskView:"}],"url":"\/documentation\/expdba\/expdba\/unmaskview(_:)"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"role":"collection","title":"EXPDBA","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","kind":"symbol","type":"topic","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.verint.xm.dba\/SQ"},"doc://com.verint.xm.dba/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.verint.xm.dba\/objc(cs)NSObject"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/isRecording()":{"role":"symbol","title":"isRecording()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRecording"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks if DBA is recording."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRecording"}],"url":"\/documentation\/expdba\/expdba\/isrecording()"},"doc://com.verint.xm.dba/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.verint.xm.dba\/s28CustomDebugStringConvertibleP"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/logPageChange(_:)":{"role":"symbol","title":"logPageChange(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logPageChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Manually adds a page break to the DBA session."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/logPageChange(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logPageChange:"}],"url":"\/documentation\/expdba\/expdba\/logpagechange(_:)"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/maskView(_:)":{"role":"symbol","title":"maskView(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Masks a view in a DBA recording."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskView(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maskView:"}],"url":"\/documentation\/expdba\/expdba\/maskview(_:)"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/setRecordingPermission(_:)":{"role":"symbol","title":"setRecordingPermission(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setRecordingPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DBAPermissionResponse","preciseIdentifier":"c:@E@DBAPermissionResponse"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables recording through use of the API or an implemented custom prompt. Includes additional options such as recording for one session only."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setRecordingPermission(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setRecordingPermission:"}],"url":"\/documentation\/expdba\/expdba\/setrecordingpermission(_:)"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/resetRecordingPermission()":{"role":"symbol","title":"resetRecordingPermission()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetRecordingPermission"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Resets recording permission to the default value of ‘NotSet’."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/resetRecordingPermission()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"resetRecordingPermission"}],"url":"\/documentation\/expdba\/expdba\/resetrecordingpermission()"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/maskedViews()":{"role":"symbol","title":"maskedViews()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"maskedViews"},{"kind":"text","text":"() -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Gets the list of masked views."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskedViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maskedViews"}],"url":"\/documentation\/expdba\/expdba\/maskedviews()"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/isMaskingDebugEnabled()":{"role":"symbol","title":"isMaskingDebugEnabled()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMaskingDebugEnabled"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checks if masking debug is enabled."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isMaskingDebugEnabled()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isMaskingDebugEnabled"}],"url":"\/documentation\/expdba\/expdba\/ismaskingdebugenabled()"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/setMaskingDebugEnabled(_:)":{"role":"symbol","title":"setMaskingDebugEnabled(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaskingDebugEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Enables masking debug which adds translucent red areas on screen to indicate masked areas."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setMaskingDebugEnabled(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setMaskingDebugEnabled:"}],"url":"\/documentation\/expdba\/expdba\/setmaskingdebugenabled(_:)"},"doc://com.verint.xm.dba/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.verint.xm.dba\/s7CVarArgP"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/stopRecordingAnd(onComplete:)":{"role":"symbol","title":"stopRecordingAnd(onComplete:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecordingAnd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onComplete"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Stops DBA recording and executes the given callback when the operation is complete."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecordingAnd(onComplete:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stopRecordingAndOnComplete:"}],"url":"\/documentation\/expdba\/expdba\/stoprecordingand(oncomplete:)"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/requestBeginRecording()":{"role":"symbol","title":"requestBeginRecording()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestBeginRecording"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Requests DBA to record the screen."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/requestBeginRecording()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestBeginRecording"}],"url":"\/documentation\/expdba\/expdba\/requestbeginrecording()"},"doc://com.verint.xm.dba/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.verint.xm.dba\/objc(pl)NSObject"},"doc://com.verint.xm.dba/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.verint.xm.dba\/s23CustomStringConvertibleP"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/setTestGroupValue(_:forKey:)":{"role":"symbol","title":"setTestGroupValue(_:forKey:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTestGroupValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Adds a test group value for the given predefined test group key."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setTestGroupValue(_:forKey:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setTestGroupValue:forKey:"}],"url":"\/documentation\/expdba\/expdba\/settestgroupvalue(_:forkey:)"},"doc://com.verint.xm.dba/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.verint.xm.dba\/SH"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"role":"symbol","title":"EXPDBA","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EXPDBA"}],"abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"url":"\/documentation\/expdba\/expdba"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"EXPDBA"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EXPDBA"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"EXPDBA"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isMaskingDebugEnabled()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/isRecording()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/logPageChange(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskView(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/maskedViews()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/requestBeginRecording()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/resetRecordingPermission()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setMaskingDebugEnabled(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setRecordingPermission(_:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setTestGroupValue(_:forKey:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecording()","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecordingAnd(onComplete:)","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/unmaskView(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.verint.xm.dba\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"EXPDBA"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecording()\/title","value":"stopRecording"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecording()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1unmaskView(_:)\/title","value":"unmaskView:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1unmaskView(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unmaskView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isRecording()\/title","value":"isRecording"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isRecording()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1logPageChange(_:)\/title","value":"logPageChange:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1logPageChange(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logPageChange:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1maskView(_:)\/title","value":"maskView:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1maskView(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"maskView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setRecordingPermission(_:)\/title","value":"setRecordingPermission:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setRecordingPermission(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setRecordingPermission:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1resetRecordingPermission()\/title","value":"resetRecordingPermission"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1resetRecordingPermission()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"resetRecordingPermission"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1maskedViews()\/title","value":"maskedViews"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1maskedViews()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"maskedViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isMaskingDebugEnabled()\/title","value":"isMaskingDebugEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1isMaskingDebugEnabled()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"isMaskingDebugEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setMaskingDebugEnabled(_:)\/title","value":"setMaskingDebugEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setMaskingDebugEnabled(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setMaskingDebugEnabled:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecordingAnd(onComplete:)\/title","value":"stopRecordingAndOnComplete:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecordingAnd(onComplete:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopRecordingAndOnComplete:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1requestBeginRecording()\/title","value":"requestBeginRecording"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1requestBeginRecording()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"requestBeginRecording"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setTestGroupValue(_:forKey:)\/title","value":"setTestGroupValue:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setTestGroupValue(_:forKey:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTestGroupValue:forKey:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","value":"EXPDBA"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"kind":"identifier","text":"EXPDBA"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}