{"kind":"symbol","identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/kTestGroupKeyPermissionPrompt","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA"]]},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"kTestGroupKeyPermissionPrompt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Global Variable","modules":[{"name":"EXPDBA"}],"title":"kTestGroupKeyPermissionPrompt","symbolKind":"var","externalID":"c:EXPDBA.h@kTestGroupKeyPermissionPrompt","navigatorTitle":[{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/expdba\/ktestgroupkeypermissionprompt"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/ktestgroupkeypermissionprompt"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","url":"\/documentation\/expdba","title":"EXPDBA","role":"collection","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","abstract":[],"kind":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA/kTestGroupKeyPermissionPrompt":{"abstract":[],"url":"\/documentation\/expdba\/ktestgroupkeypermissionprompt","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/kTestGroupKeyPermissionPrompt","navigatorTitle":[{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"kTestGroupKeyPermissionPrompt"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"kTestGroupKeyPermissionPrompt","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"value":[{"text":"kTestGroupKeyPermissionPrompt","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"kTestGroupKeyPermissionPrompt","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1kTestGroupKeyPermissionPrompt\/title","value":"kTestGroupKeyPermissionPrompt"},{"op":"replace","value":[{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1kTestGroupKeyPermissionPrompt\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}