{"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyPresented(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"metadata":{"role":"symbol","modules":[{"name":"EXPDigital"}],"externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveyPresented:","symbolKind":"method","navigatorTitle":[{"text":"digitalSurveyPresented:","kind":"identifier"}],"roleHeading":"Instance Method","title":"digitalSurveyPresented(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalSurveyPresented","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalSurveyPresented","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"surveyName","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveypresented(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveypresented(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyPresented(_:)":{"navigatorTitle":[{"text":"digitalSurveyPresented:","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyPresented(_:)","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveypresented(_:)","title":"digitalSurveyPresented(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"digitalSurveyPresented","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"url":"\/documentation\/expdigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","role":"collection","abstract":[],"type":"topic","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"url":"\/documentation\/expdigital\/digitaldelegate","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalDelegate"}],"abstract":[{"type":"text","text":"Objects that adopt the"},{"code":"DigitalDelegate","type":"codeVoice"},{"text":" protocol receive ","type":"text"},{"type":"codeVoice","code":"Digital"},{"text":" lifecycle events","type":"text"}],"type":"topic","navigatorTitle":[{"text":"DigitalDelegate","kind":"identifier"}],"title":"DigitalDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"digitalSurveyPresented:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"digitalSurveyPresented:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"digitalSurveyPresented:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"surveyName"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"digitalSurveyPresented:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyPresented(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"digitalSurveyPresented:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyPresented(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","value":"DigitalDelegate"},{"value":[{"kind":"identifier","text":"DigitalDelegate"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","op":"replace"}]}]}