{"variants":[{"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithdisabled(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithdisabled(_:)"]}],"sections":[],"kind":"symbol","metadata":{"title":"digitalSurveyNotPresentedWithDisabled(_:)","required":true,"modules":[{"name":"EXPDigital"}],"navigatorTitle":[{"kind":"identifier","text":"digitalSurveyNotPresentedWithDisabled:"}],"externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate(im)digitalSurveyNotPresentedWithDisabled:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"digitalSurveyNotPresentedWithDisabled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"digitalSurveyNotPresentedWithDisabled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"surveyName","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithDisabled(_:)"},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/expdigital","title":"EXPDigital","type":"topic"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"type":"topic","abstract":[{"type":"text","text":"Objects that adopt the"},{"type":"codeVoice","code":"DigitalDelegate"},{"text":" protocol receive ","type":"text"},{"type":"codeVoice","code":"Digital"},{"type":"text","text":" lifecycle events"}],"kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","url":"\/documentation\/expdigital\/digitaldelegate","navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"role":"symbol","title":"DigitalDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalDelegate"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotPresentedWithDisabled(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalSurveyNotPresentedWithDisabled"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"title":"digitalSurveyNotPresentedWithDisabled(_:)","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithDisabled(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"digitalSurveyNotPresentedWithDisabled:"}],"url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithdisabled(_:)","type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"digitalSurveyNotPresentedWithDisabled:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyNotPresentedWithDisabled:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"digitalSurveyNotPresentedWithDisabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"surveyName"},{"text":";","kind":"text"}]}]}},{"value":"DigitalDelegate","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title"},{"value":[{"kind":"identifier","text":"DigitalDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments"},{"value":"digitalSurveyNotPresentedWithDisabled:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithDisabled(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"digitalSurveyNotPresentedWithDisabled:"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithDisabled(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}