{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-8w8jr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-8w8jr"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-8w8jr"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(initWithEventType:surveyId:origin:) ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"eventType","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventType","text":"EXPSDKEventType"},{"text":", ","kind":"text"},{"text":"surveyId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"text":"EXPSDKEventOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"initWithEventType:surveyId:origin:","kind":"identifier"}],"title":"init(_:surveyId:origin:)","externalID":"c:@M@EXPSurveyManagement@objc(cs)SdkEvent(im)initWithEventType:surveyId:origin:","symbolKind":"init","modules":[{"name":"EXPSurveyManagement"}],"role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@EXPSDKEventType","text":"EXPSDKEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"surveyId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"text":"EXPSDKEventOrigin","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventOrigin"},{"text":")","kind":"text"}]},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/init(_:surveyId:origin:)-8w8jr":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@EXPSDKEventType","text":"EXPSDKEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"surveyId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@EXPSDKEventOrigin","kind":"typeIdentifier","text":"EXPSDKEventOrigin"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithEventType:surveyId:origin:","kind":"identifier"}],"title":"init(_:surveyId:origin:)","type":"topic","kind":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent\/init(_:surveyid:origin:)-8w8jr","role":"symbol","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/init(_:surveyId:origin:)-8w8jr"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","title":"SdkEvent","navigatorTitle":[{"text":"SdkEvent","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkEvent","kind":"identifier"}],"url":"\/documentation\/expsurveymanagement\/sdkevent"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","url":"\/documentation\/expsurveymanagement","abstract":[],"role":"collection","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","kind":"symbol","title":"EXPSurveyManagement"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithEventType:surveyId:origin:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithEventType:surveyId:origin:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithEventType:"},{"text":"(","kind":"text"},{"text":"EXPSDKEventType","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"eventType"},{"text":" ","kind":"text"},{"text":"surveyId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"surveyId"},{"kind":"text","text":" "},{"text":"origin:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EXPSDKEventOrigin","preciseIdentifier":"c:@E@EXPSDKEventOrigin"},{"kind":"text","text":") "},{"text":"origin","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-8w8jr\/title","value":"initWithEventType:surveyId:origin:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1init(_:surveyId:origin:)-8w8jr\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithEventType:surveyId:origin:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title","value":"SdkEvent","op":"replace"},{"op":"replace","value":[{"text":"SdkEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}