{"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setEventTrigger"},{"kind":"text","text":"("},{"text":"eventTrigger","kind":"externalParam"},{"kind":"text","text":": "},{"text":"EXPSDKEventTrigger","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventTrigger"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/seteventtrigger(eventtrigger:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/seteventtrigger(eventtrigger:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setEventTrigger","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eventTrigger"},{"text":": ","kind":"text"},{"text":"EXPSDKEventTrigger","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventTrigger"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setEventTriggerWithEventTrigger:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@EXPSurveyManagement@objc(cs)SdkEvent(im)setEventTriggerWithEventTrigger:","symbolKind":"method","role":"symbol","modules":[{"name":"EXPSurveyManagement"}],"title":"setEventTrigger(eventTrigger:)"},"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setEventTrigger(eventTrigger:)","interfaceLanguage":"swift"},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/setEventTrigger(eventTrigger:)":{"navigatorTitle":[{"kind":"identifier","text":"setEventTriggerWithEventTrigger:"}],"kind":"symbol","abstract":[],"url":"\/documentation\/expsurveymanagement\/sdkevent\/seteventtrigger(eventtrigger:)","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/setEventTrigger(eventTrigger:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setEventTrigger","kind":"identifier"},{"kind":"text","text":"("},{"text":"eventTrigger","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@EXPSDKEventTrigger","text":"EXPSDKEventTrigger","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"setEventTrigger(eventTrigger:)","type":"topic","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","title":"EXPSurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","url":"\/documentation\/expsurveymanagement","kind":"symbol","role":"collection","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SdkEvent","kind":"identifier"}],"abstract":[],"title":"SdkEvent","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SdkEvent","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","url":"\/documentation\/expsurveymanagement\/sdkevent"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setEventTriggerWithEventTrigger:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setEventTriggerWithEventTrigger:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setEventTriggerWithEventTrigger:"},{"kind":"text","text":"("},{"text":"EXPSDKEventTrigger","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPSDKEventTrigger"},{"kind":"text","text":") "},{"text":"eventTrigger","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1setEventTrigger(eventTrigger:)\/title","value":"setEventTriggerWithEventTrigger:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1setEventTrigger(eventTrigger:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setEventTriggerWithEventTrigger:"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title","op":"replace","value":"SdkEvent"},{"value":[{"kind":"identifier","text":"SdkEvent"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}