{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setContactDetails(_:for:)"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EXPPredictiveFacade.setContactDetails(_:for:)"},{"type":"text","text":"."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/setcontactdetails(_:for:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/setcontactdetails(_:for:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)setContactDetails:forType:","role":"symbol","modules":[{"name":"EXPSurveyManagement"}],"title":"setContactDetails(_:for:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setContactDetails","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPContactType","text":"EXPContactType"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"setContactDetails:forType:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setContactDetails","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"contactDetails","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPContactType","text":"EXPContactType"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"url":"\/documentation\/expsurveymanagement\/surveymanagement","kind":"symbol","abstract":[],"title":"SurveyManagement","navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SurveyManagement","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setContactDetails(_:for:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setContactDetails(_:for:)","type":"topic","role":"symbol","kind":"symbol","title":"setContactDetails(_:for:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setContactDetails"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@EXPContactType","text":"EXPContactType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"setContactDetails:forType:","kind":"identifier"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/setcontactdetails(_:for:)","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"title":"EXPSurveyManagement","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"setContactDetails:forType:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setContactDetails:forType:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setContactDetails:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contactDetails"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forType:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPContactType","text":"EXPContactType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"EXPSurveyManagement","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","value":[{"text":"EXPSurveyManagement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setContactDetails(_:for:)\/title","op":"replace","value":"setContactDetails:forType:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setContactDetails(_:for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setContactDetails:forType:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}