{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)showInviteForName:","role":"symbol","modules":[{"name":"EXPSurveyManagement"}],"title":"showInvite(forName:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showInvite"},{"kind":"text","text":"("},{"text":"forName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"showInviteForName:"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showInvite"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forName"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/showinvite(forname:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/showinvite(forname:)"]}],"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showInvite(forName:)","interfaceLanguage":"swift"},"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/showInvite(forName:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showInvite(forName:)","type":"topic","role":"symbol","kind":"symbol","title":"showInvite(forName:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showInvite"},{"kind":"text","text":"("},{"text":"forName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"showInviteForName:","kind":"identifier"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/showinvite(forname:)","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"title":"EXPSurveyManagement","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","role":"collection"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"url":"\/documentation\/expsurveymanagement\/surveymanagement","kind":"symbol","abstract":[],"title":"SurveyManagement","navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SurveyManagement","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"showInviteForName:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showInviteForName:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"showInviteForName:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"showInviteForName:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showInvite(forName:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showInvite(forName:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"showInviteForName:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","value":"EXPSurveyManagement"},{"value":[{"kind":"identifier","text":"EXPSurveyManagement"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}