{"topicSections":[{"identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/HooverLogger"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/kTestGroupKeyPermissionPrompt"]},{"identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"],"title":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/UIKit"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"EXPDBA","roleHeading":"Framework","role":"collection","modules":[{"name":"EXPDBA"}],"externalID":"EXPDBA","symbolKind":"module"},"sections":[],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"variants":[{"paths":["\/documentation\/expdba"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba"]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate":{"navigatorTitle":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate","url":"\/documentation\/expdba\/dbahooverconnectiondelegate","abstract":[],"role":"symbol","type":"topic","title":"DBAHooverConnectionDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"kind":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"abstract":[],"role":"collection","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","kind":"symbol","title":"EXPDBA","type":"topic","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAPermissionResponse":{"title":"DBAPermissionResponse","navigatorTitle":[{"text":"DBAPermissionResponse","kind":"identifier"}],"abstract":[],"url":"\/documentation\/expdba\/dbapermissionresponse","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DBAPermissionResponse"}],"type":"topic","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"type":"topic","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","role":"symbol","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}],"title":"EXPDBA","kind":"symbol","url":"\/documentation\/expdba\/expdba","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EXPDBA","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/kTestGroupKeyPermissionPrompt":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"kTestGroupKeyPermissionPrompt","role":"symbol","url":"\/documentation\/expdba\/ktestgroupkeypermissionprompt","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/kTestGroupKeyPermissionPrompt"},"doc://com.verint.xm.dba/documentation/EXPDBA/HooverLogger":{"navigatorTitle":[{"kind":"identifier","text":"HooverLogger"}],"abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/HooverLogger","kind":"symbol","url":"\/documentation\/expdba\/hooverlogger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HooverLogger","kind":"identifier"}],"title":"HooverLogger","type":"topic","role":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA/UIKit":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/UIKit","role":"collection","type":"topic","title":"UIKit","url":"\/documentation\/expdba\/uikit","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Classes","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]},{"title":"Protocols","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate"]},{"title":"Variables","identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/kTestGroupKeyPermissionPrompt"]},{"identifiers":["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAPermissionResponse"],"title":"Enumerations"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"DBAHooverConnectionDelegate","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/title","op":"replace"},{"op":"replace","value":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/title","value":"DBAPermissionResponse"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAPermissionResponse\/fragments","value":[{"text":"DBAPermissionResponse","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","op":"replace","value":"EXPDBA"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","op":"replace","value":[{"text":"EXPDBA","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1kTestGroupKeyPermissionPrompt\/title","value":"kTestGroupKeyPermissionPrompt"},{"value":[{"kind":"identifier","text":"kTestGroupKeyPermissionPrompt"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1kTestGroupKeyPermissionPrompt\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}