{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"platforms":[{"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false}],"navigatorTitle":[{"text":"setMaskingDebugEnabled:","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)EXPDBA(cm)setMaskingDebugEnabled:","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMaskingDebugEnabled"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Type Method","title":"setMaskingDebugEnabled(_:)","modules":[{"name":"EXPDBA"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"sections":[],"abstract":[{"text":"Enables masking debug which adds translucent red areas on screen to indicate masked areas.","type":"text"}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setMaskingDebugEnabled(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setMaskingDebugEnabled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"enabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"enabled","content":[{"inlineContent":[{"type":"text","text":"YES to enable masking debug, NO to disable"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Disabled by default and must be called after the SDK is started."}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/setmaskingdebugenabled(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/setmaskingdebugenabled(_:)"]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"role":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EXPDBA","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","kind":"symbol","title":"EXPDBA","url":"\/documentation\/expdba\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/setMaskingDebugEnabled(_:)":{"url":"\/documentation\/expdba\/expdba\/setmaskingdebugenabled(_:)","abstract":[{"text":"Enables masking debug which adds translucent red areas on screen to indicate masked areas.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setMaskingDebugEnabled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setMaskingDebugEnabled:","kind":"identifier"}],"kind":"symbol","title":"setMaskingDebugEnabled(_:)","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setMaskingDebugEnabled(_:)"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","title":"EXPDBA","kind":"symbol","url":"\/documentation\/expdba","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"setMaskingDebugEnabled:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"setMaskingDebugEnabled:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setMaskingDebugEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"enabled","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","value":"EXPDBA"},{"value":[{"text":"EXPDBA","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setMaskingDebugEnabled(_:)\/title","op":"replace","value":"setMaskingDebugEnabled:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setMaskingDebugEnabled(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setMaskingDebugEnabled:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}