{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopRecordingAnd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onComplete"},{"kind":"text","text":" "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is an asynchronous operation."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If DBA is not recording, calling this method has no effect."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecordingAnd(onComplete:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdba\/expdba\/stoprecordingand(oncomplete:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/stoprecordingand(oncomplete:)"]}],"sections":[],"metadata":{"platforms":[{"beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iOS"}],"roleHeading":"Type Method","modules":[{"name":"EXPDBA"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopRecordingAnd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"onComplete","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stopRecordingAndOnComplete:"}],"title":"stopRecordingAnd(onComplete:)","externalID":"c:objc(cs)EXPDBA(cm)stopRecordingAndOnComplete:"},"kind":"symbol","abstract":[{"type":"text","text":"Stops DBA recording and executes the given callback when the operation is complete."}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","title":"EXPDBA","kind":"symbol","url":"\/documentation\/expdba","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/stopRecordingAnd(onComplete:)":{"url":"\/documentation\/expdba\/expdba\/stoprecordingand(oncomplete:)","abstract":[{"text":"Stops DBA recording and executes the given callback when the operation is complete.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecordingAnd"},{"kind":"text","text":"("},{"text":"onComplete","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"stopRecordingAndOnComplete:","kind":"identifier"}],"kind":"symbol","title":"stopRecordingAnd(onComplete:)","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecordingAnd(onComplete:)"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"role":"symbol","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EXPDBA","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","kind":"symbol","title":"EXPDBA","url":"\/documentation\/expdba\/expdba"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"stopRecordingAndOnComplete:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"stopRecordingAndOnComplete:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"stopRecordingAndOnComplete:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFv()"},{"kind":"text","text":") "},{"text":"callback","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecordingAnd(onComplete:)\/title","value":"stopRecordingAndOnComplete:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecordingAnd(onComplete:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"stopRecordingAndOnComplete:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","op":"replace","value":"EXPDBA"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"kind":"identifier","text":"EXPDBA"}]}]}]}