{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalDelegate"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/expdigital\/digitaldelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdigital\/digitaldelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate"},"metadata":{"symbolKind":"protocol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"title":"DigitalDelegate","role":"symbol","modules":[{"name":"EXPDigital"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}],"externalID":"c:@M@EXPDigital@objc(pl)DigitalDelegate"},"abstract":[{"text":"Objects that adopt the","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"type":"codeVoice","code":"Digital"},{"type":"text","text":" lifecycle events"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithDisabled(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithNetworkError(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithAbort(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithNetworkError(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyPresented(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyStatusRetrieved(_:enabled:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveySubmitted(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotSubmittedWithNetworkError(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithNetworkError(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"digitalSurveyNotSubmittedWithNetworkError:"}],"url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithnetworkerror(_:)","type":"topic","title":"digitalSurveyNotSubmittedWithNetworkError(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"digitalSurveyNotSubmittedWithNetworkError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate":{"title":"DigitalDelegate","url":"\/documentation\/expdigital\/digitaldelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalDelegate"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate","abstract":[{"text":"Objects that adopt the","type":"text"},{"code":"DigitalDelegate","type":"codeVoice"},{"type":"text","text":" protocol receive "},{"type":"codeVoice","code":"Digital"},{"text":" lifecycle events","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DigitalDelegate","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveySubmitted(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveySubmitted(_:)","type":"topic","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveysubmitted(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveySubmitted"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"digitalSurveySubmitted:","kind":"identifier"}],"title":"digitalSurveySubmitted(_:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotSubmittedWithAbort(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithAbort(_:)","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"digitalSurveyNotSubmittedWithAbort:"}],"url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotsubmittedwithabort(_:)","type":"topic","abstract":[],"title":"digitalSurveyNotSubmittedWithAbort(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"digitalSurveyNotSubmittedWithAbort"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital","role":"collection","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyPresented(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyPresented(_:)","type":"topic","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveypresented(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalSurveyPresented","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"required":true,"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"digitalSurveyPresented:","kind":"identifier"}],"title":"digitalSurveyPresented(_:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyStatusRetrieved(_:enabled:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyStatusRetrieved(_:enabled:)","type":"topic","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveystatusretrieved(_:enabled:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveyStatusRetrieved"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"enabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"required":true,"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"digitalSurveyStatusRetrieved:enabled:","kind":"identifier"}],"title":"digitalSurveyStatusRetrieved(_:enabled:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotPresentedWithNetworkError(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithNetworkError(_:)","type":"topic","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithnetworkerror(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"digitalSurveyNotPresentedWithNetworkError"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"digitalSurveyNotPresentedWithNetworkError:","kind":"identifier"}],"title":"digitalSurveyNotPresentedWithNetworkError(_:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalDelegate/digitalSurveyNotPresentedWithDisabled(_:)":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithDisabled(_:)","type":"topic","url":"\/documentation\/expdigital\/digitaldelegate\/digitalsurveynotpresentedwithdisabled(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"digitalSurveyNotPresentedWithDisabled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"required":true,"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"digitalSurveyNotPresentedWithDisabled:","kind":"identifier"}],"title":"digitalSurveyNotPresentedWithDisabled(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"DigitalDelegate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DigitalDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DigitalDelegate","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithDisabled(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotPresentedWithNetworkError(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithAbort(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyNotSubmittedWithNetworkError(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyPresented(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveyStatusRetrieved(_:enabled:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalDelegate\/digitalSurveySubmitted(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalDelegate"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithNetworkError(_:)\/title","op":"replace","value":"digitalSurveyNotSubmittedWithNetworkError:"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithNetworkError(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"digitalSurveyNotSubmittedWithNetworkError:","kind":"identifier"}],"op":"replace"},{"value":"DigitalDelegate","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate\/fragments","value":[{"kind":"identifier","text":"DigitalDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveySubmitted(_:)\/title","value":"digitalSurveySubmitted:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"digitalSurveySubmitted:"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveySubmitted(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithAbort(_:)\/title","value":"digitalSurveyNotSubmittedWithAbort:"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotSubmittedWithAbort(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"digitalSurveyNotSubmittedWithAbort:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyPresented(_:)\/title","value":"digitalSurveyPresented:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"digitalSurveyPresented:"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyPresented(_:)\/fragments"},{"op":"replace","value":"digitalSurveyStatusRetrieved:enabled:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyStatusRetrieved(_:enabled:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyStatusRetrieved(_:enabled:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"digitalSurveyStatusRetrieved:enabled:","kind":"identifier"}]},{"value":"digitalSurveyNotPresentedWithNetworkError:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithNetworkError(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"digitalSurveyNotPresentedWithNetworkError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithNetworkError(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithDisabled(_:)\/title","value":"digitalSurveyNotPresentedWithDisabled:","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalDelegate~1digitalSurveyNotPresentedWithDisabled(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"digitalSurveyNotPresentedWithDisabled:","kind":"identifier"}],"op":"replace"}]}]}