{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionString"},"metadata":{"symbolKind":"var","externalID":"c:@DigitalVersionString","title":"DigitalVersionString","navigatorTitle":[{"kind":"identifier","text":"DigitalVersionString"}],"role":"symbol","modules":[{"name":"EXPDigital"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalVersionString"},{"kind":"text","text":": <<error type>>"}],"roleHeading":"Global Variable"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Project version string for Digital."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalversionstring"]},{"paths":["\/documentation\/expdigital\/digitalversionstring"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalVersionString"},{"kind":"text","text":": <<error type>>"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalVersionString":{"kind":"symbol","url":"\/documentation\/expdigital\/digitalversionstring","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalVersionString","title":"DigitalVersionString","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DigitalVersionString"}],"role":"symbol","abstract":[{"type":"text","text":"Project version string for Digital."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalVersionString"},{"text":": <<error type>>","kind":"text"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital","role":"collection","title":"EXPDigital"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DigitalVersionString"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DigitalVersionString"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalVersionString"},{"text":"[]","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DigitalVersionString","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionString\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalVersionString\/fragments","value":[{"kind":"identifier","text":"DigitalVersionString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}