{"abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DigitalComponent) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DigitalComponent"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalComponent","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent","roleHeading":"Class","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"title":"DigitalComponent","modules":[{"name":"EXPDigital"}],"symbolKind":"class"},"sections":[],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.Verint.EXPDigital\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.Verint.EXPDigital\/objc(pl)NSObject","doc:\/\/com.Verint.EXPDigital\/s7CVarArgP","doc:\/\/com.Verint.EXPDigital\/s28CustomDebugStringConvertibleP","doc:\/\/com.Verint.EXPDigital\/s23CustomStringConvertibleP","doc:\/\/com.Verint.EXPDigital\/SQ","doc:\/\/com.Verint.EXPDigital\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital"]]},"variants":[{"paths":["\/documentation\/expdigital\/digitalcomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdigital\/digitalcomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/isEnabled()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onSetupComplete()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onUnhandledException()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/resetState()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setup()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/delegate"]},{"title":"Type Methods","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/availableDigitalSurveyNames()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabled()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabledForName(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setDigitalListener(delegate:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurvey()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurveyForName(_:)"]}],"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","interfaceLanguage":"swift"},"references":{"doc://com.Verint.EXPDigital/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.Verint.EXPDigital\/objc(pl)NSObject"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/showDigitalSurvey()":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showDigitalSurvey"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"showDigitalSurvey","kind":"identifier"}],"title":"showDigitalSurvey()","url":"\/documentation\/expdigital\/digitalcomponent\/showdigitalsurvey()","abstract":[{"type":"text","text":"Shows the default Digital survey (i.e. the first survey defined in the configuration)"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurvey()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/availableDigitalSurveyNames()":{"title":"availableDigitalSurveyNames()","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/availableDigitalSurveyNames()","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"availableDigitalSurveyNames","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"availableDigitalSurveyNames"}],"type":"topic","url":"\/documentation\/expdigital\/digitalcomponent\/availabledigitalsurveynames()","abstract":[{"type":"text","text":"Gets a list of available Digital surveys"}],"role":"symbol"},"doc://com.Verint.EXPDigital/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.Verint.EXPDigital\/SQ"},"doc://com.Verint.EXPDigital/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.Verint.EXPDigital\/objc(cs)NSObject"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/onSetupComplete()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onSetupComplete","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"onSetupComplete","kind":"identifier"}],"title":"onSetupComplete()","url":"\/documentation\/expdigital\/digitalcomponent\/onsetupcomplete()","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onSetupComplete()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/checkIfDigitalSurveyEnabled()":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkIfDigitalSurveyEnabled","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkIfDigitalSurveyEnabled"}],"title":"checkIfDigitalSurveyEnabled()","url":"\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabled()","abstract":[{"type":"text","text":"Checks whether a default Digital survey is enabled."}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabled()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/setup()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setup"}],"title":"setup()","url":"\/documentation\/expdigital\/digitalcomponent\/setup()","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setup()"},"doc://com.Verint.EXPDigital/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.Verint.EXPDigital\/s23CustomStringConvertibleP"},"doc://com.Verint.EXPDigital/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.Verint.EXPDigital\/SH"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital","role":"collection","title":"EXPDigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/checkIfDigitalSurveyEnabledForName(_:)":{"abstract":[{"type":"text","text":"Checks whether a Digital survey with the given name is enabled"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"checkIfDigitalSurveyEnabledForName:"}],"url":"\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabledforname(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkIfDigitalSurveyEnabledForName"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabledForName(_:)","kind":"symbol","title":"checkIfDigitalSurveyEnabledForName(_:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/init":{"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","url":"\/documentation\/expdigital\/digitalcomponent\/init","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/init"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/delegate":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DigitalDelegate","preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate","url":"\/documentation\/expdigital\/digitalcomponent\/delegate","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/delegate"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"navigatorTitle":[{"kind":"identifier","text":"DigitalComponent"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","role":"symbol","kind":"symbol","abstract":[{"text":"The primary interface for showing Verint Digital surveys","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DigitalComponent","kind":"identifier"}],"title":"DigitalComponent","url":"\/documentation\/expdigital\/digitalcomponent"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/setDigitalListener(delegate:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDigitalListener"},{"kind":"text","text":"("},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EXPDigital@objc(pl)DigitalDelegate","text":"DigitalDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"setDigitalListenerWithDelegate:","kind":"identifier"}],"title":"setDigitalListener(delegate:)","url":"\/documentation\/expdigital\/digitalcomponent\/setdigitallistener(delegate:)","abstract":[{"text":"Sets a delegate for Digital survey operations","type":"text"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setDigitalListener(delegate:)"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/isEnabled()":{"navigatorTitle":[{"text":"isEnabled","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/isEnabled()","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEnabled"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEnabled()","url":"\/documentation\/expdigital\/digitalcomponent\/isenabled()"},"doc://com.Verint.EXPDigital/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.Verint.EXPDigital\/s7CVarArgP","type":"unresolvable"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/onUnhandledException()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUnhandledException","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"onUnhandledException","kind":"identifier"}],"title":"onUnhandledException()","url":"\/documentation\/expdigital\/digitalcomponent\/onunhandledexception()","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onUnhandledException()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/resetState()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetState","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"resetState","kind":"identifier"}],"title":"resetState()","url":"\/documentation\/expdigital\/digitalcomponent\/resetstate()","abstract":[],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/resetState()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/showDigitalSurveyForName(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showDigitalSurveyForName","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"showDigitalSurveyForName:","kind":"identifier"}],"title":"showDigitalSurveyForName(_:)","url":"\/documentation\/expdigital\/digitalcomponent\/showdigitalsurveyforname(_:)","abstract":[{"text":"Shows the Digital survey configured for the given name","type":"text"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurveyForName(_:)"},"doc://com.Verint.EXPDigital/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.Verint.EXPDigital\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DigitalComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DigitalComponent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DigitalComponent","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/init","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/isEnabled()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onSetupComplete()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onUnhandledException()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/resetState()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setup()"]},{"title":"Type Properties","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/delegate"]},{"title":"Type Methods","identifiers":["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/availableDigitalSurveyNames()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabled()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabledForName(_:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/setDigitalListener(delegate:)","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurvey()","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurveyForName(_:)"]}]},{"value":[{"identifiers":["doc:\/\/com.Verint.EXPDigital\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DigitalComponent","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurvey()\/title","value":"showDigitalSurvey","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurvey()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showDigitalSurvey","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1availableDigitalSurveyNames()\/title","value":"availableDigitalSurveyNames"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1availableDigitalSurveyNames()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"availableDigitalSurveyNames","kind":"identifier"}],"op":"replace"},{"value":"onSetupComplete","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onSetupComplete()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onSetupComplete()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onSetupComplete"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabled()\/title","op":"replace","value":"checkIfDigitalSurveyEnabled"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabled()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"checkIfDigitalSurveyEnabled","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"setup","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setup()\/title"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setup()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setup"}],"op":"replace"},{"op":"replace","value":"checkIfDigitalSurveyEnabledForName:","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabledForName(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"checkIfDigitalSurveyEnabledForName:"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabledForName(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1delegate\/title","value":"delegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","op":"replace","value":"DigitalComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","value":[{"text":"DigitalComponent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setDigitalListener(delegate:)\/title","value":"setDigitalListenerWithDelegate:"},{"value":[{"text":"+ ","kind":"text"},{"text":"setDigitalListenerWithDelegate:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1setDigitalListener(delegate:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1isEnabled()\/title","value":"isEnabled"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEnabled"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1isEnabled()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onUnhandledException()\/title","value":"onUnhandledException"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onUnhandledException","kind":"identifier"}],"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onUnhandledException()\/fragments"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1resetState()\/title","op":"replace","value":"resetState"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1resetState()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resetState","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurveyForName(_:)\/title","value":"showDigitalSurveyForName:"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurveyForName(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showDigitalSurveyForName:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}