{"abstract":[{"type":"text","text":"Checks whether a Digital survey with the given name is enabled"}],"metadata":{"navigatorTitle":[{"text":"checkIfDigitalSurveyEnabledForName:","kind":"identifier"}],"modules":[{"name":"EXPDigital"}],"role":"symbol","title":"checkIfDigitalSurveyEnabledForName(_:)","roleHeading":"Type Method","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(cm)checkIfDigitalSurveyEnabledForName:","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"checkIfDigitalSurveyEnabledForName","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"checkIfDigitalSurveyEnabledForName","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"the name of the survey to check","type":"text"}],"type":"paragraph"}],"name":"name"}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The status is returned to ","type":"text"},{"type":"codeVoice","code":"digitalSurveyStatusRetrieved"},{"text":" for the active","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"DigitalDelegate"},{"text":". This method returns no value.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabledforname(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabledforname(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabledForName(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalComponent"}],"abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent","type":"topic","url":"\/documentation\/expdigital\/digitalcomponent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DigitalComponent"}],"title":"DigitalComponent","kind":"symbol"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/checkIfDigitalSurveyEnabledForName(_:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/checkIfDigitalSurveyEnabledForName(_:)","url":"\/documentation\/expdigital\/digitalcomponent\/checkifdigitalsurveyenabledforname(_:)","abstract":[{"type":"text","text":"Checks whether a Digital survey with the given name is enabled"}],"title":"checkIfDigitalSurveyEnabledForName(_:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkIfDigitalSurveyEnabledForName"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"checkIfDigitalSurveyEnabledForName:","kind":"identifier"}]},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/expdigital","title":"EXPDigital","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"checkIfDigitalSurveyEnabledForName:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"checkIfDigitalSurveyEnabledForName:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"checkIfDigitalSurveyEnabledForName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"name"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","value":"DigitalComponent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","value":[{"kind":"identifier","text":"DigitalComponent"}]},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabledForName(_:)\/title","op":"replace","value":"checkIfDigitalSurveyEnabledForName:"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1checkIfDigitalSurveyEnabledForName(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"checkIfDigitalSurveyEnabledForName:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}