{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)EXPPredictiveFacade","doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSObject","doc:\/\/com.verint.xm.EXPSurveyManagement\/s7CVarArgP","doc:\/\/com.verint.xm.EXPSurveyManagement\/s28CustomDebugStringConvertibleP","doc:\/\/com.verint.xm.EXPSurveyManagement\/s23CustomStringConvertibleP","doc:\/\/com.verint.xm.EXPSurveyManagement\/SQ","doc:\/\/com.verint.xm.EXPSurveyManagement\/SH"],"title":"Conforms To"}],"kind":"symbol","metadata":{"symbolKind":"class","title":"SurveyManagement","externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SurveyManagement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}],"roleHeading":"Class","modules":[{"name":"EXPSurveyManagement"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(EXPSurveyManagement) "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement"]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement"]]},"topicSections":[{"identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/isEnabled()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onSetupComplete()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onUnhandledException()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetState()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setup()"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/allContactDetails()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/cancelPendingNotifications()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/checkIfEligibleForSurvey()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/clearUserData()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/contactDetails(for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteAccepted()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteDeclined()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementPageViews()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCount(withKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCountAndCheckEligibility(withKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/preferredContactType()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEventCount(forKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEvents()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setContactDetails(_:for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setPreferredContactType(_:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setSignificantEventCount(_:forKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setSkipPoolingCheck(_:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/shouldSkipPoolingCheck()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showInvite(forName:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(forName:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/surveyId(for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/unifySampling(forWebView:)"]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","url":"\/documentation\/expsurveymanagement\/surveymanagement","title":"SurveyManagement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SurveyManagement","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/showInvite(forName:)":{"abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showInvite","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showInvite(forName:)","kind":"symbol","title":"showInvite(forName:)","type":"topic","url":"\/documentation\/expsurveymanagement\/surveymanagement\/showinvite(forname:)","navigatorTitle":[{"text":"showInviteForName:","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/contactDetails(for:)":{"kind":"symbol","title":"contactDetails(for:)","abstract":[],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/contactdetails(for:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contactDetails"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EXPContactType","preciseIdentifier":"c:@E@EXPContactType"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/contactDetails(for:)","role":"symbol","navigatorTitle":[{"text":"contactDetailsForType:","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/objc(pl)EXPPredictiveFacade":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)EXPPredictiveFacade","title":"EXPPredictiveFacade","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/showSurvey(for:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSurvey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"text":": ","kind":"text"},{"text":"UNNotificationResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UNNotificationResponse"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/showsurvey(for:)","title":"showSurvey(for:)","navigatorTitle":[{"text":"showSurveyForNotificationResponse:","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(for:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/EXPSurveyManagement/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","kind":"symbol","abstract":[],"url":"\/documentation\/expsurveymanagement\/expsurveymanagement\/init","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPSurveyManagement\/init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/s23CustomStringConvertibleP"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setPreferredContactType(_:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setPreferredContactType(_:)","type":"topic","title":"setPreferredContactType(_:)","abstract":[],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/setpreferredcontacttype(_:)","navigatorTitle":[{"text":"setPreferredContactType:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setPreferredContactType"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EXPContactType","preciseIdentifier":"c:@E@EXPContactType"},{"text":")","kind":"text"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/incrementSignificantEventCountAndCheckEligibility(withKey:)":{"navigatorTitle":[{"kind":"identifier","text":"incrementSignificantEventCountAndCheckEligibilityWithKey:"}],"title":"incrementSignificantEventCountAndCheckEligibility(withKey:)","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCountAndCheckEligibility(withKey:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"incrementSignificantEventCountAndCheckEligibility"},{"text":"(","kind":"text"},{"text":"withKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/incrementsignificanteventcountandcheckeligibility(withkey:)","kind":"symbol","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/s7CVarArgP"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/incrementPageViews()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementPageViews()","type":"topic","kind":"symbol","abstract":[],"title":"incrementPageViews()","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"incrementPageViews"},{"kind":"text","text":"()"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/incrementpageviews()","navigatorTitle":[{"text":"incrementPageViews","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/customInviteAccepted()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteAccepted()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customInviteAccepted"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"customInviteAccepted"}],"type":"topic","abstract":[],"kind":"symbol","title":"customInviteAccepted()","url":"\/documentation\/expsurveymanagement\/surveymanagement\/custominviteaccepted()","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/checkIfEligibleForSurvey()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/checkIfEligibleForSurvey()","title":"checkIfEligibleForSurvey()","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkIfEligibleForSurvey"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/checkifeligibleforsurvey()","navigatorTitle":[{"text":"checkIfEligibleForSurvey","kind":"identifier"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/isEnabled()":{"url":"\/documentation\/expsurveymanagement\/surveymanagement\/isenabled()","navigatorTitle":[{"text":"isEnabled","kind":"identifier"}],"type":"topic","title":"isEnabled()","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEnabled"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/isEnabled()","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/customInviteDeclined()":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"customInviteDeclined"},{"text":"()","kind":"text"}],"title":"customInviteDeclined()","navigatorTitle":[{"text":"customInviteDeclined","kind":"identifier"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/custominvitedeclined()","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteDeclined()","abstract":[],"type":"topic","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/shouldSkipPoolingCheck()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/shouldSkipPoolingCheck()","title":"shouldSkipPoolingCheck()","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shouldSkipPoolingCheck","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/shouldskippoolingcheck()","navigatorTitle":[{"kind":"identifier","text":"shouldSkipPoolingCheck"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/SQ","title":"Swift.Equatable"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/incrementSignificantEventCount(withKey:)":{"navigatorTitle":[{"kind":"identifier","text":"incrementSignificantEventCountWithKey:"}],"title":"incrementSignificantEventCount(withKey:)","type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCount(withKey:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"incrementSignificantEventCount","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/incrementsignificanteventcount(withkey:)","kind":"symbol","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/clearUserData()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/clearUserData()","title":"clearUserData()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearUserData","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/clearuserdata()","type":"topic","abstract":[],"navigatorTitle":[{"text":"clearUserData","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/allContactDetails()":{"url":"\/documentation\/expsurveymanagement\/surveymanagement\/allcontactdetails()","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"allContactDetails"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allContactDetails","kind":"identifier"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/allContactDetails()","kind":"symbol","title":"allContactDetails()"},"doc://com.verint.xm.EXPSurveyManagement/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/onSetupComplete()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onSetupComplete()","title":"onSetupComplete()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSetupComplete"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/onsetupcomplete()","navigatorTitle":[{"text":"onSetupComplete","kind":"identifier"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/unifySampling(forWebView:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/unifySampling(forWebView:)","kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/unifysampling(forwebview:)","title":"unifySampling(forWebView:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unifySampling","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forWebView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"unifySamplingForWebView:"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/resetState()":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetState","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","title":"resetState()","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetState()","url":"\/documentation\/expsurveymanagement\/surveymanagement\/resetstate()","type":"topic","navigatorTitle":[{"text":"resetState","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","type":"topic","title":"EXPSurveyManagement","kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"role":"collection"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/showSurvey(forName:)":{"type":"topic","title":"showSurvey(forName:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showSurvey"},{"text":"(","kind":"text"},{"text":"forName","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"showSurveyForName:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/showsurvey(forname:)","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(forName:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setSignificantEventCount(_:forKey:)":{"title":"setSignificantEventCount(_:forKey:)","url":"\/documentation\/expsurveymanagement\/surveymanagement\/setsignificanteventcount(_:forkey:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSignificantEventCount"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setSignificantEventCount(_:forKey:)","navigatorTitle":[{"kind":"identifier","text":"setSignificantEventCount:forKey:"}]},"doc://com.verint.xm.EXPSurveyManagement/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(cs)NSObject"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/onUnhandledException()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onUnhandledException()","title":"onUnhandledException()","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUnhandledException"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/onunhandledexception()","navigatorTitle":[{"kind":"identifier","text":"onUnhandledException"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/surveyId(for:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/surveyId(for:)","abstract":[],"title":"surveyId(for:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"surveyId","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UNNotificationResponse","text":"UNNotificationResponse","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/surveyid(for:)","kind":"symbol","navigatorTitle":[{"text":"surveyIdForNotificationResponse:","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setup()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","title":"setup()","navigatorTitle":[{"text":"setup","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setup()","url":"\/documentation\/expsurveymanagement\/surveymanagement\/setup()","role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setSkipPoolingCheck(_:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setSkipPoolingCheck(_:)","title":"setSkipPoolingCheck(_:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSkipPoolingCheck","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/setskippoolingcheck(_:)","navigatorTitle":[{"text":"setSkipPoolingCheck:","kind":"identifier"}],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setContactDetails(_:for:)":{"type":"topic","title":"setContactDetails(_:for:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setContactDetails","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"EXPContactType","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPContactType"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/setcontactdetails(_:for:)","navigatorTitle":[{"text":"setContactDetails:forType:","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setContactDetails(_:for:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/resetSignificantEventCount(forKey:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"resetSignificantEventCountForKey:"}],"type":"topic","title":"resetSignificantEventCount(forKey:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetSignificantEventCount"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEventCount(forKey:)","url":"\/documentation\/expsurveymanagement\/surveymanagement\/resetsignificanteventcount(forkey:)"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/preferredContactType()":{"type":"topic","title":"preferredContactType()","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"preferredContactType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"EXPContactType","preciseIdentifier":"c:@E@EXPContactType","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/preferredcontacttype()","navigatorTitle":[{"text":"preferredContactType","kind":"identifier"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/preferredContactType()"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/cancelPendingNotifications()":{"type":"topic","title":"cancelPendingNotifications()","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelPendingNotifications"},{"text":"()","kind":"text"}],"kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/cancelpendingnotifications()","navigatorTitle":[{"kind":"identifier","text":"cancelPendingNotifications"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/cancelPendingNotifications()"},"doc://com.verint.xm.EXPSurveyManagement/SH":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/resetSignificantEvents()":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resetSignificantEvents","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEvents()","navigatorTitle":[{"text":"resetSignificantEvents","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement\/resetsignificantevents()","role":"symbol","abstract":[],"title":"resetSignificantEvents()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"EXPSurveyManagement"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"EXPSurveyManagement"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"EXPSurveyManagement","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPSurveyManagement\/init","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/isEnabled()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onSetupComplete()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/onUnhandledException()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetState()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setup()"]},{"title":"Type Methods","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/allContactDetails()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/cancelPendingNotifications()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/checkIfEligibleForSurvey()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/clearUserData()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/contactDetails(for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteAccepted()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteDeclined()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementPageViews()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCount(withKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCountAndCheckEligibility(withKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/preferredContactType()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEventCount(forKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/resetSignificantEvents()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setContactDetails(_:for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setPreferredContactType(_:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setSignificantEventCount(_:forKey:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setSkipPoolingCheck(_:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/shouldSkipPoolingCheck()","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showInvite(forName:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/showSurvey(forName:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/surveyId(for:)","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/unifySampling(forWebView:)"]}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/objc(pl)EXPPredictiveFacade"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EXPSurveyManagement"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","op":"replace","value":"EXPSurveyManagement"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","op":"replace","value":[{"kind":"identifier","text":"EXPSurveyManagement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showInvite(forName:)\/title","value":"showInviteForName:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showInvite(forName:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showInviteForName:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1contactDetails(for:)\/title","value":"contactDetailsForType:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"contactDetailsForType:"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1contactDetails(for:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showSurvey(for:)\/title","value":"showSurveyForNotificationResponse:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showSurvey(for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showSurveyForNotificationResponse:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"setPreferredContactType:","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setPreferredContactType(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"setPreferredContactType:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setPreferredContactType(_:)\/fragments"},{"value":"incrementSignificantEventCountAndCheckEligibilityWithKey:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementSignificantEventCountAndCheckEligibility(withKey:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementSignificantEventCountAndCheckEligibility(withKey:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"incrementSignificantEventCountAndCheckEligibilityWithKey:"}]},{"value":"incrementPageViews","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementPageViews()\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementPageViews()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"incrementPageViews","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1customInviteAccepted()\/title","value":"customInviteAccepted"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1customInviteAccepted()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"customInviteAccepted"}]},{"op":"replace","value":"checkIfEligibleForSurvey","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1checkIfEligibleForSurvey()\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1checkIfEligibleForSurvey()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"checkIfEligibleForSurvey","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1isEnabled()\/title","value":"isEnabled"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEnabled"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1isEnabled()\/fragments","op":"replace"},{"value":"customInviteDeclined","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1customInviteDeclined()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1customInviteDeclined()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"customInviteDeclined","kind":"identifier"}]},{"op":"replace","value":"shouldSkipPoolingCheck","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1shouldSkipPoolingCheck()\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1shouldSkipPoolingCheck()\/fragments","value":[{"kind":"text","text":"+ "},{"text":"shouldSkipPoolingCheck","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementSignificantEventCount(withKey:)\/title","op":"replace","value":"incrementSignificantEventCountWithKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementSignificantEventCount(withKey:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"incrementSignificantEventCountWithKey:"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1clearUserData()\/title","op":"replace","value":"clearUserData"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1clearUserData()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"clearUserData","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1allContactDetails()\/title","value":"allContactDetails"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1allContactDetails()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"allContactDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onSetupComplete()\/title","value":"onSetupComplete"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onSetupComplete()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onSetupComplete","kind":"identifier"}],"op":"replace"},{"value":"unifySamplingForWebView:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1unifySampling(forWebView:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unifySamplingForWebView:"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1unifySampling(forWebView:)\/fragments"},{"value":"resetState","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetState()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetState()\/fragments","value":[{"kind":"text","text":"- "},{"text":"resetState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showSurvey(forName:)\/title","value":"showSurveyForName:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"showSurveyForName:"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1showSurvey(forName:)\/fragments"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setSignificantEventCount(_:forKey:)\/title","op":"replace","value":"setSignificantEventCount:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setSignificantEventCount(_:forKey:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"setSignificantEventCount:forKey:"}]},{"value":"onUnhandledException","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onUnhandledException()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1onUnhandledException()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUnhandledException","kind":"identifier"}]},{"value":"surveyIdForNotificationResponse:","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1surveyId(for:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1surveyId(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"surveyIdForNotificationResponse:"}],"op":"replace"},{"value":"setup","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setup()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setup()\/fragments","value":[{"kind":"text","text":"- "},{"text":"setup","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setSkipPoolingCheck(_:)\/title","op":"replace","value":"setSkipPoolingCheck:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setSkipPoolingCheck(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setSkipPoolingCheck:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setContactDetails(_:for:)\/title","value":"setContactDetails:forType:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setContactDetails(_:for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"setContactDetails:forType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetSignificantEventCount(forKey:)\/title","op":"replace","value":"resetSignificantEventCountForKey:"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetSignificantEventCount(forKey:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"resetSignificantEventCountForKey:"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1preferredContactType()\/title","op":"replace","value":"preferredContactType"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1preferredContactType()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"preferredContactType","kind":"identifier"}]},{"value":"cancelPendingNotifications","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1cancelPendingNotifications()\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"cancelPendingNotifications","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1cancelPendingNotifications()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetSignificantEvents()\/title","value":"resetSignificantEvents"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"resetSignificantEvents"}],"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1resetSignificantEvents()\/fragments"}]}]}