{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/onsetupcomplete()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/onsetupcomplete()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onSetupComplete()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"EXPDigital"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onSetupComplete","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"onSetupComplete"}],"roleHeading":"Instance Method","title":"onSetupComplete()","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(im)onSetupComplete"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onSetupComplete"},{"kind":"text","text":"()"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"sections":[],"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"url":"\/documentation\/expdigital\/digitalcomponent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalComponent"}],"kind":"symbol","title":"DigitalComponent","role":"symbol","abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"type":"topic","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/onSetupComplete()":{"url":"\/documentation\/expdigital\/digitalcomponent\/onsetupcomplete()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onSetupComplete"},{"text":"()","kind":"text"}],"kind":"symbol","title":"onSetupComplete()","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"onSetupComplete"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/onSetupComplete()"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"role":"collection","type":"topic","title":"EXPDigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onSetupComplete","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onSetupComplete"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onSetupComplete"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","op":"replace","value":"DigitalComponent"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","op":"replace","value":[{"text":"DigitalComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onSetupComplete()\/title","value":"onSetupComplete","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onSetupComplete"}],"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1onSetupComplete()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}