{"sections":[],"metadata":{"modules":[{"name":"EXPDigital"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showDigitalSurvey","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(cm)showDigitalSurvey","title":"showDigitalSurvey()","navigatorTitle":[{"kind":"identifier","text":"showDigitalSurvey"}],"roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showDigitalSurvey","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Shows the default Digital survey (i.e. the first survey defined in the configuration)"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/showdigitalsurvey()"]},{"paths":["\/documentation\/expdigital\/digitalcomponent\/showdigitalsurvey()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurvey()"},"hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"url":"\/documentation\/expdigital\/digitalcomponent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalComponent"}],"kind":"symbol","title":"DigitalComponent","role":"symbol","abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"type":"topic","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"role":"collection","type":"topic","title":"EXPDigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/showDigitalSurvey()":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showDigitalSurvey"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","title":"showDigitalSurvey()","navigatorTitle":[{"text":"showDigitalSurvey","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Shows the default Digital survey (i.e. the first survey defined in the configuration)"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurvey()","url":"\/documentation\/expdigital\/digitalcomponent\/showdigitalsurvey()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"showDigitalSurvey","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"showDigitalSurvey","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"showDigitalSurvey"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"DigitalComponent","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","op":"replace","value":[{"text":"DigitalComponent","kind":"identifier"}]},{"value":"showDigitalSurvey","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurvey()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurvey()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"showDigitalSurvey"}]}]}]}