{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"]]},"variants":[{"paths":["\/documentation\/expdigital\/digitalcomponent\/showdigitalsurveyforname(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdigital\/digitalcomponent\/showdigitalsurveyforname(_:)"]}],"abstract":[{"text":"Shows the Digital survey configured for the given name","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showDigitalSurveyForName","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"name","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"the name of the survey to show"}]}]}],"kind":"parameters"}],"metadata":{"role":"symbol","title":"showDigitalSurveyForName(_:)","navigatorTitle":[{"kind":"identifier","text":"showDigitalSurveyForName:"}],"modules":[{"name":"EXPDigital"}],"externalID":"c:@M@EXPDigital@objc(cs)DigitalComponent(cm)showDigitalSurveyForName:","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showDigitalSurveyForName","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"roleHeading":"Type Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurveyForName(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent":{"url":"\/documentation\/expdigital\/digitalcomponent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DigitalComponent"}],"kind":"symbol","title":"DigitalComponent","role":"symbol","abstract":[{"type":"text","text":"The primary interface for showing Verint Digital surveys"}],"type":"topic","navigatorTitle":[{"text":"DigitalComponent","kind":"identifier"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent"},"doc://com.Verint.EXPDigital/documentation/EXPDigital":{"abstract":[],"role":"collection","type":"topic","title":"EXPDigital","kind":"symbol","identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital","url":"\/documentation\/expdigital"},"doc://com.Verint.EXPDigital/documentation/EXPDigital/DigitalComponent/showDigitalSurveyForName(_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDigitalSurveyForName"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"showDigitalSurveyForName(_:)","navigatorTitle":[{"text":"showDigitalSurveyForName:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Shows the Digital survey configured for the given name","type":"text"}],"identifier":"doc:\/\/com.Verint.EXPDigital\/documentation\/EXPDigital\/DigitalComponent\/showDigitalSurveyForName(_:)","url":"\/documentation\/expdigital\/digitalcomponent\/showdigitalsurveyforname(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"showDigitalSurveyForName:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"showDigitalSurveyForName:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showDigitalSurveyForName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DigitalComponent","op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent\/fragments","value":[{"text":"DigitalComponent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurveyForName(_:)\/title","value":"showDigitalSurveyForName:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.Verint.EXPDigital~1documentation~1EXPDigital~1DigitalComponent~1showDigitalSurveyForName(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"showDigitalSurveyForName:","kind":"identifier"}]}]}]}