{"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]},{"title":"Extended Modules","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPPredictive_Private"]}],"kind":"symbol","metadata":{"title":"EXPSurveyManagement","externalID":"EXPSurveyManagement","symbolKind":"module","roleHeading":"Framework","modules":[{"name":"EXPSurveyManagement"}],"role":"collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement"]},{"paths":["\/documentation\/expsurveymanagement"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"sections":[],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"role":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SdkEvent"}],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","title":"SdkEvent","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SdkEvent","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/EXPSurveyManagementVersionString":{"role":"symbol","url":"\/documentation\/expsurveymanagement\/expsurveymanagementversionstring","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPSurveyManagementVersionString","title":"EXPSurveyManagementVersionString","type":"topic","abstract":[{"text":"Project version string for EXPSurveyManagement.","type":"text"}],"fragments":[{"kind":"identifier","text":"EXPSurveyManagementVersionString"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/EXPSurveyManagementVersionNumber":{"role":"symbol","url":"\/documentation\/expsurveymanagement\/expsurveymanagementversionnumber","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPSurveyManagementVersionNumber","title":"EXPSurveyManagementVersionNumber","type":"topic","abstract":[{"type":"text","text":"Project version number for EXPSurveyManagement."}],"fragments":[{"text":"EXPSurveyManagementVersionNumber","kind":"identifier"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"type":"topic","role":"collection","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","url":"\/documentation\/expsurveymanagement","title":"EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/EXPPredictive_Private":{"role":"collection","url":"\/documentation\/expsurveymanagement\/exppredictive_private","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPPredictive_Private","title":"EXPPredictive_Private","type":"topic","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"title":"SurveyManagement","abstract":[],"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","role":"symbol","kind":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SurveyManagement","kind":"identifier"}],"navigatorTitle":[{"text":"SurveyManagement","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]},{"title":"Variables","identifiers":["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPSurveyManagementVersionNumber","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/EXPSurveyManagementVersionString"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"SdkEvent","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments","op":"replace","value":[{"text":"SdkEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title","value":"EXPSurveyManagement"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","op":"replace","value":[{"kind":"identifier","text":"EXPSurveyManagement"}]}]}]}