{"metadata":{"navigatorTitle":[{"text":"websocketConnected","kind":"identifier"}],"role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"websocketConnected","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"EXPDBA"}],"roleHeading":"Instance Method","externalID":"c:@M@EXPDBA@objc(pl)DBAHooverConnectionDelegate(im)websocketConnected","title":"websocketConnected()","symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"websocketConnected","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketconnected()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketconnected()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketConnected()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate"]]},"sections":[],"kind":"symbol","references":{"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate/websocketConnected()":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate\/websocketConnected()","abstract":[],"type":"topic","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"websocketConnected"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"websocketConnected","kind":"identifier"}],"kind":"symbol","title":"websocketConnected()","url":"\/documentation\/expdba\/dbahooverconnectiondelegate\/websocketconnected()"},"doc://com.verint.xm.dba/documentation/EXPDBA/DBAHooverConnectionDelegate":{"url":"\/documentation\/expdba\/dbahooverconnectiondelegate","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"navigatorTitle":[{"text":"DBAHooverConnectionDelegate","kind":"identifier"}],"kind":"symbol","title":"DBAHooverConnectionDelegate","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/DBAHooverConnectionDelegate"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","title":"EXPDBA","kind":"symbol","url":"\/documentation\/expdba","abstract":[],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"websocketConnected","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"websocketConnected","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"websocketConnected"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketConnected()\/title","value":"websocketConnected","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate~1websocketConnected()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"websocketConnected"}]},{"value":"DBAHooverConnectionDelegate","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/title"},{"value":[{"kind":"identifier","text":"DBAHooverConnectionDelegate"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1DBAHooverConnectionDelegate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}