{"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"logPageChange:"}],"role":"symbol","title":"logPageChange(_:)","modules":[{"name":"EXPDBA"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logPageChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)EXPDBA(cm)logPageChange:","symbolKind":"method","platforms":[{"name":"iOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"logPageChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"pageName","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"pageName","content":[{"type":"paragraph","inlineContent":[{"text":"The name of the page displayed in the player","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"This is not required in most cases as changes between UIViewControllers are detected automatically."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/logPageChange(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Manually adds a page break to the DBA session."}],"variants":[{"paths":["\/documentation\/expdba\/expdba\/logpagechange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/logpagechange(_:)"]}],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/logPageChange(_:)":{"navigatorTitle":[{"text":"logPageChange:","kind":"identifier"}],"title":"logPageChange(_:)","role":"symbol","type":"topic","url":"\/documentation\/expdba\/expdba\/logpagechange(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logPageChange"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/logPageChange(_:)","abstract":[{"type":"text","text":"Manually adds a page break to the DBA session."}]},"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","url":"\/documentation\/expdba","title":"EXPDBA","role":"collection","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","abstract":[],"kind":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","title":"EXPDBA","abstract":[{"text":"The EXPDBA class provides the main interface to the DBA module. This module requires the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EXPDBA"}],"kind":"symbol","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}],"url":"\/documentation\/expdba\/expdba","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"logPageChange:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"logPageChange:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"logPageChange:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"pageName","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"logPageChange:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1logPageChange(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"logPageChange:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1logPageChange(_:)\/fragments"},{"value":"EXPDBA","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","value":[{"text":"EXPDBA","kind":"identifier"}],"op":"replace"}]}]}