{"identifier":{"url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/requestBeginRecording()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/expdba\/expdba\/requestbeginrecording()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expdba\/expdba\/requestbeginrecording()"]}],"abstract":[{"type":"text","text":"Requests DBA to record the screen."}],"metadata":{"symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"requestBeginRecording","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"requestBeginRecording()","externalID":"c:objc(cs)EXPDBA(cm)requestBeginRecording","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false}],"navigatorTitle":[{"text":"requestBeginRecording","kind":"identifier"}],"modules":[{"name":"EXPDBA"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestBeginRecording"},{"text":"()","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Displays a dialog which asks the user for permission. Recording starts if the user agrees."},{"text":" ","type":"text"},{"text":"If DBA is already recording (or in a state which prevents a new recording), calling this method has no effect.","type":"text"}]}]}],"sections":[],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/requestBeginRecording()":{"type":"topic","navigatorTitle":[{"text":"requestBeginRecording","kind":"identifier"}],"url":"\/documentation\/expdba\/expdba\/requestbeginrecording()","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/requestBeginRecording()","abstract":[{"type":"text","text":"Requests DBA to record the screen."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestBeginRecording"},{"text":"()","kind":"text"}],"title":"requestBeginRecording()","role":"symbol","kind":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA":{"url":"\/documentation\/expdba","title":"EXPDBA","kind":"symbol","type":"topic","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","abstract":[],"role":"collection"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"kind":"symbol","title":"EXPDBA","type":"topic","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EXPDBA"}],"url":"\/documentation\/expdba\/expdba","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","abstract":[{"type":"text","text":"The EXPDBA class provides the main interface to the DBA module. This module requires the"},{"text":" ","type":"text"},{"type":"text","text":"primary EXPCore.framework."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"requestBeginRecording","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"requestBeginRecording","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"requestBeginRecording","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1requestBeginRecording()\/title","value":"requestBeginRecording","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"requestBeginRecording","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1requestBeginRecording()\/fragments"},{"value":"EXPDBA","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","op":"replace"},{"value":[{"kind":"identifier","text":"EXPDBA"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}