{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setTestGroupValue(_:forKey:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Adds a test group value for the given predefined test group key."}],"variants":[{"paths":["\/documentation\/expdba\/expdba\/settestgroupvalue(_:forkey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/expdba\/settestgroupvalue(_:forkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"setTestGroupValue(_:forKey:)","symbolKind":"method","navigatorTitle":[{"text":"setTestGroupValue:forKey:","kind":"identifier"}],"externalID":"c:objc(cs)EXPDBA(cm)setTestGroupValue:forKey:","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setTestGroupValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"modules":[{"name":"EXPDBA"}],"platforms":[{"beta":false,"unavailable":false,"introducedAt":"13.0","name":"iOS","deprecated":false}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setTestGroupValue"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":" "},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"a new value for the given key"}]}],"name":"value"},{"content":[{"inlineContent":[{"text":"the test group key","type":"text"}],"type":"paragraph"}],"name":"key"}]}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"sections":[],"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"type":"topic","url":"\/documentation\/expdba","title":"EXPDBA","role":"collection","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","abstract":[],"kind":"symbol"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/setTestGroupValue(_:forKey:)":{"role":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/setTestGroupValue(_:forKey:)","navigatorTitle":[{"kind":"identifier","text":"setTestGroupValue:forKey:"}],"abstract":[{"text":"Adds a test group value for the given predefined test group key.","type":"text"}],"url":"\/documentation\/expdba\/expdba\/settestgroupvalue(_:forkey:)","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setTestGroupValue","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","title":"setTestGroupValue(_:forKey:)"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","title":"EXPDBA","abstract":[{"text":"The EXPDBA class provides the main interface to the DBA module. This module requires the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"primary EXPCore.framework."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EXPDBA"}],"kind":"symbol","navigatorTitle":[{"text":"EXPDBA","kind":"identifier"}],"url":"\/documentation\/expdba\/expdba","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"setTestGroupValue:forKey:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setTestGroupValue:forKey:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"setTestGroupValue:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"forKey:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"setTestGroupValue:forKey:","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setTestGroupValue(_:forKey:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"setTestGroupValue:forKey:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1setTestGroupValue(_:forKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title","value":"EXPDBA"},{"value":[{"text":"EXPDBA","kind":"identifier"}],"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}