{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This is an asynchronous operation.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"If DBA is not recording, calling this method has no effect.","type":"text"}]}],"kind":"content"}],"kind":"symbol","variants":[{"paths":["\/documentation\/expdba\/expdba\/stoprecording()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/expdba\/expdba\/stoprecording()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Stops DBA recording."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecording()"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"EXPDBA"}],"navigatorTitle":[{"kind":"identifier","text":"stopRecording"}],"symbolKind":"method","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0"}],"title":"stopRecording()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopRecording"},{"text":"()","kind":"text"}],"externalID":"c:objc(cs)EXPDBA(cm)stopRecording","roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA"]]},"references":{"doc://com.verint.xm.dba/documentation/EXPDBA":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA","type":"topic","role":"collection","title":"EXPDBA","url":"\/documentation\/expdba"},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA":{"url":"\/documentation\/expdba\/expdba","abstract":[{"text":"The EXPDBA class provides the main interface to the DBA module. This module requires the","type":"text"},{"type":"text","text":" "},{"text":"primary EXPCore.framework.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EXPDBA"}],"title":"EXPDBA","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EXPDBA","kind":"identifier"}]},"doc://com.verint.xm.dba/documentation/EXPDBA/EXPDBA/stopRecording()":{"type":"topic","abstract":[{"type":"text","text":"Stops DBA recording."}],"role":"symbol","url":"\/documentation\/expdba\/expdba\/stoprecording()","navigatorTitle":[{"text":"stopRecording","kind":"identifier"}],"kind":"symbol","title":"stopRecording()","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopRecording","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/com.verint.xm.dba\/documentation\/EXPDBA\/EXPDBA\/stopRecording()"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"value":"stopRecording","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"stopRecording"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stopRecording","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"EXPDBA","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/title"},{"value":[{"kind":"identifier","text":"EXPDBA"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA\/fragments"},{"value":"stopRecording","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecording()\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.dba~1documentation~1EXPDBA~1EXPDBA~1stopRecording()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"stopRecording","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}