{"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent"]]},"metadata":{"title":"addCustomParameter(key:value:)","modules":[{"name":"EXPSurveyManagement"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addCustomParameter","kind":"identifier"},{"kind":"text","text":"("},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"externalID":"c:@M@EXPSurveyManagement@objc(cs)SdkEvent(im)addCustomParameterWithKey:value:","symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addCustomParameterWithKey:value:"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/expsurveymanagement\/sdkevent\/addcustomparameter(key:value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/sdkevent\/addcustomparameter(key:value:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addCustomParameter","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/addCustomParameter(key:value:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SdkEvent","kind":"identifier"}],"title":"SdkEvent","url":"\/documentation\/expsurveymanagement\/sdkevent","kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent","abstract":[],"navigatorTitle":[{"text":"SdkEvent","kind":"identifier"}],"role":"symbol"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","kind":"symbol","role":"collection","url":"\/documentation\/expsurveymanagement","title":"EXPSurveyManagement"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SdkEvent/addCustomParameter(key:value:)":{"role":"symbol","url":"\/documentation\/expsurveymanagement\/sdkevent\/addcustomparameter(key:value:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCustomParameter"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SdkEvent\/addCustomParameter(key:value:)","type":"topic","abstract":[],"title":"addCustomParameter(key:value:)","navigatorTitle":[{"text":"addCustomParameterWithKey:value:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"addCustomParameterWithKey:value:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCustomParameterWithKey:value:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"addCustomParameterWithKey:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/title","value":"SdkEvent"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent\/fragments","value":[{"text":"SdkEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1addCustomParameter(key:value:)\/title","value":"addCustomParameterWithKey:value:"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SdkEvent~1addCustomParameter(key:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCustomParameterWithKey:value:"}]}]}]}