{"metadata":{"externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)customInviteDeclined","title":"customInviteDeclined()","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"customInviteDeclined"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"customInviteDeclined"},{"text":"()","kind":"text"}],"roleHeading":"Type Method","modules":[{"name":"EXPSurveyManagement"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EXPPredictiveFacade.customInviteDeclined()"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteDeclined()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"customInviteDeclined","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/custominvitedeclined()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/custominvitedeclined()"]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"kind":"symbol","title":"SurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}],"abstract":[],"role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement","navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"title":"EXPSurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","role":"collection","kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/customInviteDeclined()":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/customInviteDeclined()","title":"customInviteDeclined()","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"customInviteDeclined"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/custominvitedeclined()","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customInviteDeclined","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"customInviteDeclined","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"customInviteDeclined"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"customInviteDeclined"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"EXPSurveyManagement","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments","op":"replace","value":[{"kind":"identifier","text":"EXPSurveyManagement"}]},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1customInviteDeclined()\/title","value":"customInviteDeclined","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1customInviteDeclined()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"customInviteDeclined","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}