{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"identifier":{"url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCountAndCheckEligibility(withKey:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)incrementSignificantEventCountAndCheckEligibilityWithKey:","navigatorTitle":[{"text":"incrementSignificantEventCountAndCheckEligibilityWithKey:","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incrementSignificantEventCountAndCheckEligibility","kind":"identifier"},{"kind":"text","text":"("},{"text":"withKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"incrementSignificantEventCountAndCheckEligibility(withKey:)","modules":[{"name":"EXPSurveyManagement"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EXPPredictiveFacade.incrementSignificantEventCountAndCheckEligibility(withKey:)"},{"text":".","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/incrementsignificanteventcountandcheckeligibility(withkey:)"]},{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/incrementsignificanteventcountandcheckeligibility(withkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"incrementSignificantEventCountAndCheckEligibility","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withKey","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"title":"EXPSurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","role":"collection","kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/incrementSignificantEventCountAndCheckEligibility(withKey:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/incrementSignificantEventCountAndCheckEligibility(withKey:)","title":"incrementSignificantEventCountAndCheckEligibility(withKey:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"incrementSignificantEventCountAndCheckEligibilityWithKey:","kind":"identifier"}],"url":"\/documentation\/expsurveymanagement\/surveymanagement\/incrementsignificanteventcountandcheckeligibility(withkey:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"incrementSignificantEventCountAndCheckEligibility","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"kind":"symbol","title":"SurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}],"abstract":[],"role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement","navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"incrementSignificantEventCountAndCheckEligibilityWithKey:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"incrementSignificantEventCountAndCheckEligibilityWithKey:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"incrementSignificantEventCountAndCheckEligibilityWithKey:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementSignificantEventCountAndCheckEligibility(withKey:)\/title","value":"incrementSignificantEventCountAndCheckEligibilityWithKey:","op":"replace"},{"path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1incrementSignificantEventCountAndCheckEligibility(withKey:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"incrementSignificantEventCountAndCheckEligibilityWithKey:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"EXPSurveyManagement","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title"},{"value":[{"text":"EXPSurveyManagement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments"}]}]}