{"hierarchy":{"paths":[["doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setPreferredContactType"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@EXPContactType","text":"EXPContactType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","externalID":"c:@M@EXPSurveyManagement@objc(cs)EXPSurveyManagement(cm)setPreferredContactType:","navigatorTitle":[{"text":"setPreferredContactType:","kind":"identifier"}],"modules":[{"name":"EXPSurveyManagement"}],"roleHeading":"Type Method","title":"setPreferredContactType(_:)"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setPreferredContactType(_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EXPPredictiveFacade.setPreferredContactType(_:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreferredContactType","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":": "},{"text":"EXPContactType","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPContactType"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/setpreferredcontacttype(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/expsurveymanagement\/surveymanagement\/setpreferredcontacttype(_:)"]}],"references":{"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement":{"title":"EXPSurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement","role":"collection","kind":"symbol","url":"\/documentation\/expsurveymanagement","abstract":[],"type":"topic"},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement/setPreferredContactType(_:)":{"identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement\/setPreferredContactType(_:)","url":"\/documentation\/expsurveymanagement\/surveymanagement\/setpreferredcontacttype(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setPreferredContactType:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setPreferredContactType","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@EXPContactType","text":"EXPContactType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"setPreferredContactType(_:)","type":"topic","kind":"symbol","abstract":[]},"doc://com.verint.xm.EXPSurveyManagement/documentation/EXPSurveyManagement/SurveyManagement":{"kind":"symbol","title":"SurveyManagement","identifier":"doc:\/\/com.verint.xm.EXPSurveyManagement\/documentation\/EXPSurveyManagement\/SurveyManagement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SurveyManagement"}],"abstract":[],"role":"symbol","url":"\/documentation\/expsurveymanagement\/surveymanagement","navigatorTitle":[{"kind":"identifier","text":"SurveyManagement"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"setPreferredContactType:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"setPreferredContactType:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"setPreferredContactType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EXPContactType","kind":"typeIdentifier","preciseIdentifier":"c:@E@EXPContactType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setPreferredContactType(_:)\/title","value":"setPreferredContactType:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setPreferredContactType:"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement~1setPreferredContactType(_:)\/fragments"},{"value":"EXPSurveyManagement","op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/title"},{"value":[{"kind":"identifier","text":"EXPSurveyManagement"}],"op":"replace","path":"\/references\/doc:~1~1com.verint.xm.EXPSurveyManagement~1documentation~1EXPSurveyManagement~1SurveyManagement\/fragments"}]}]}